-- 318_seed_machine_translations_sept14.sql
--
-- Machine-translated proposal seeds (es/ru/uk/sv) for the client strings the Sept 14
-- Player Cards feature batch added (9 keys, 36 pairs). Same contract as
-- 184/189/213/223/239/243/249/256/265/289/291/303/313: PENDING proposals only, sentinel
-- proposer 'claude-mt', license_assent TRUE at the machine-translation terms revision. The
-- same 36 translations ship BUNDLED in I18nCatalogues.cs, so the client renders them
-- without approval; these proposals exist so human translators can see/refine them through
-- the portal (an approval overrides the bundled value via the pack overlay).
--
-- key_id = sha1("client" || chr(0) || source)[:16] - the NUL-separator form
-- tools/i18n_sync_keys.py uses.
--
-- ORDERING: seeds only keys already present in i18n_keys. Run order:
-- deploy API -> apply 317 (or run tools/i18n_sync_keys.py) -> apply this
-- file. On an unsynced database the assertion below RAISEs and the transaction
-- rolls back; re-run after the keys land. Explicit BEGIN/COMMIT (#340); every
-- statement is idempotent under the wrapper's || re-run (#243).
BEGIN;

CREATE TEMP TABLE _seed318 (
  key_id      VARCHAR(16) NOT NULL,
  lang        VARCHAR(8)  NOT NULL,
  source_hash VARCHAR(40) NOT NULL,
  target      TEXT        NOT NULL
) ON COMMIT DROP;

INSERT INTO _seed318 (key_id, lang, source_hash, target) VALUES
  -- "Slowing down - the server asked for a {0} s pause"
     ('224e05bb1d48afda', 'es', 'b7c63b7e968511515555b759c3790baa9a887cb3', E'Bajando el ritmo - el servidor pidió una pausa de {0} s')
  ,  ('224e05bb1d48afda', 'ru', 'b7c63b7e968511515555b759c3790baa9a887cb3', E'Сбавляем темп - сервер попросил паузу в {0} с')
  ,  ('224e05bb1d48afda', 'uk', 'b7c63b7e968511515555b759c3790baa9a887cb3', E'Сповільнюємось - сервер попросив паузу на {0} с')
  ,  ('224e05bb1d48afda', 'sv', 'b7c63b7e968511515555b759c3790baa9a887cb3', E'Saktar ner - servern bad om en paus på {0} s')
  -- "<color=#FFD94D><b>THE HEADER</b></color>  - The player's cur"
  ,  ('6262aad1393e919b', 'es', 'cbb4762519e994327916a66f9a48f529d91a6de7', E'<color=#FFD94D><b>LA CABECERA</b></color>\n\n- El nombre actual del jugador - un cambio de nombre se refleja en todas sus cartas - y debajo el título de la tienda que llevaba cuando se tomó la instantánea (nada si lleva el título de rango o ningún título).\n- La ficha de la esquina es la rareza: COM, UNC, RARE, EPIC o LEG, con FOIL debajo en una foil.\n\n<color=#FFD94D><b>LA IMAGEN</b></color>\n\n- El personaje del propio jugador en el juego - cuerpo, cara, color y efecto - una vez que su PC lo ha enviado. Hasta entonces, su imagen de perfil de Steam. Ver <color=#7FD4FF>Imágenes y ajustes de las cartas</color>.\n- La esquina inferior izquierda muestra su carta top: la carta de ROUNDS que, según la instantánea, eligen más que ninguna otra. Dentro del juego se dibuja a partir de la carta misma; las cartas mostradas fuera del juego (Discord) llevan ahí una insignia sencilla, y el nombre está en el bloque de texto cuando no se muestra la imagen.\n\n<color=#FFD94D><b>LAS ESTADÍSTICAS</b></color>\n\n- <b>RANK</b> es el nivel de rating en el que estaba el jugador en la instantánea - de Principiante I a Gran Maestro V, los mismos niveles que la clasificación. Nunca es el título de la tienda.\n- <b>RATING</b> es su rating en la instantánea, o Unranked.\n- <b>POOL #</b> es su posición en el pool de cartas en la instantánea - el orden que decide la rareza (ver Player Cards). Un número más bajo es una carta más rara.\n- <b>BOARD #</b> es su posición en la clasificación en la instantánea: cinco o más series clasificatorias y actividad reciente. Un guion significa que ese día no estaba en la tabla.\n- <b>RECORD</b> son las series clasificatorias ganadas y perdidas en la instantánea.\n\n<color=#FFD94D><b>LAS MARCAS</b></color>\n\n- Una carta <b>Firmada</b> lleva el autógrafo del jugador sobre la imagen y un sello.\n- El borde inferior tiene la edición, la fecha de acuñación y el número de impresión de tu copia. Haz clic en una casilla del álbum para ver la carta a tamaño completo.')
  ,  ('6262aad1393e919b', 'ru', 'cbb4762519e994327916a66f9a48f529d91a6de7', E'<color=#FFD94D><b>ШАПКА</b></color>\n\n- Текущее имя игрока - переименование подхватывается на всех его картах - а под ним титул из магазина, который он носил в момент снимка (пусто, если он носит ранговый титул или вообще без титула).\n- Значок в углу - редкость: COM, UNC, RARE, EPIC или LEG, а под ним FOIL на фольгированной.\n\n<color=#FFD94D><b>КАРТИНКА</b></color>\n\n- Собственный игровой персонаж игрока - тело, лицо, цвет и эффект - как только его ПК их отправил. До тех пор - его картинка профиля Steam. См. <color=#7FD4FF>Картинки и настройки карт</color>.\n- В левом нижнем углу показана его топ-карта: карта ROUNDS, которую, по снимку, он берёт чаще любой другой. В игре она рисуется из самой карты; у карт, показанных вне игры (Discord), там стоит простой значок, а название стоит в текстовом блоке, когда картинка не показана.\n\n<color=#FFD94D><b>СТАТИСТИКА</b></color>\n\n- <b>RANK</b> - рейтинговая ступень, на которой игрок был в момент снимка - от Новичок I до Грандмастер V, те же ступени, что в таблице лидеров. Это никогда не титул из магазина.\n- <b>RATING</b> - его рейтинг в момент снимка или Unranked.\n- <b>POOL #</b> - его позиция в пуле карт в момент снимка - порядок, который решает редкость (см. Player Cards). Чем меньше число, тем реже карта.\n- <b>BOARD #</b> - его позиция в таблице лидеров в момент снимка: пять и больше рейтинговых серий и недавняя активность. Прочерк означает, что в тот день его не было в таблице.\n- <b>RECORD</b> - выигранные и проигранные рейтинговые серии в момент снимка.\n\n<color=#FFD94D><b>ОТМЕТКИ</b></color>\n\n- <b>Подписанная</b> карта несёт автограф игрока поверх картинки и печать.\n- На нижнем крае - издание, дата выпуска и номер экземпляра твоей копии. Нажми на плитку альбома, чтобы увидеть карту в полный размер.')
  ,  ('6262aad1393e919b', 'uk', 'cbb4762519e994327916a66f9a48f529d91a6de7', E'<color=#FFD94D><b>ШАПКА</b></color>\n\n- Поточне ім''я гравця - перейменування підхоплюється на всіх його картках - а під ним титул із крамниці, який він носив у момент знімка (порожньо, якщо він носить ранговий титул або взагалі без титулу).\n- Значок у кутку - рідкість: COM, UNC, RARE, EPIC або LEG, а під ним FOIL на фольгованій.\n\n<color=#FFD94D><b>ЗОБРАЖЕННЯ</b></color>\n\n- Власний ігровий персонаж гравця - тіло, обличчя, колір і ефект - щойно його ПК їх надіслав. До того - його зображення профілю Steam. Див. <color=#7FD4FF>Зображення та налаштування карток</color>.\n- У лівому нижньому кутку показано його топ-картку: картку ROUNDS, яку, за знімком, він бере частіше за будь-яку іншу. У грі її намальовано з самої картки; у карток, показаних поза грою (Discord), там стоїть простий значок, а назва стоїть у текстовому блоці, коли зображення не показано.\n\n<color=#FFD94D><b>СТАТИСТИКА</b></color>\n\n- <b>RANK</b> - рейтинговий щабель, на якому гравець був у момент знімка - від Новачок I до Грандмайстер V, ті самі щаблі, що й у таблиці лідерів. Це ніколи не титул із крамниці.\n- <b>RATING</b> - його рейтинг у момент знімка або Unranked.\n- <b>POOL #</b> - його позиція в пулі карток у момент знімка - порядок, який вирішує рідкість (див. Player Cards). Що менше число, то рідкісніша картка.\n- <b>BOARD #</b> - його позиція в таблиці лідерів у момент знімка: п''ять і більше рейтингових серій і недавня активність. Риска означає, що того дня його не було в таблиці.\n- <b>RECORD</b> - виграні й програні рейтингові серії в момент знімка.\n\n<color=#FFD94D><b>ПОЗНАЧКИ</b></color>\n\n- <b>Підписана</b> картка несе автограф гравця поверх зображення й печатку.\n- На нижньому краї - видання, дата випуску та номер примірника вашої копії. Натисніть на плитку альбому, щоб побачити картку в повний розмір.')
  ,  ('6262aad1393e919b', 'sv', 'cbb4762519e994327916a66f9a48f529d91a6de7', E'<color=#FFD94D><b>SIDHUVUDET</b></color>\n\n- Spelarens nuvarande namn - ett namnbyte följer med på varje kort av dem - och under det butikstiteln de bar när ögonblicksbilden togs (tomt om de bär rangtiteln eller ingen titel alls).\n- Brickan i hörnet är sällsyntheten: COM, UNC, RARE, EPIC eller LEG, med FOIL under på en foil.\n\n<color=#FFD94D><b>BILDEN</b></color>\n\n- Spelarens egen spelfigur - kropp, ansikte, färg och effekt - när deras dator har skickat den. Fram till dess deras Steam-profilbild. Se <color=#7FD4FF>Kortbilder & inställningar</color>.\n- Nedre vänstra hörnet visar deras toppkort: det ROUNDS-kort som ögonblicksbilden hittade att de väljer oftare än något annat. I spelet ritas det från själva kortet; kort som visas utanför spelet (Discord) bär ett enkelt märke där i stället, och namnet står på textblocket när bilden inte visas.\n\n<color=#FFD94D><b>STATISTIKEN</b></color>\n\n- <b>RANK</b> är ratingnivån spelaren låg på vid ögonblicksbilden - Nybörjare I upp till Stormästare V, samma nivåer som topplistan. Det är aldrig butikstiteln.\n- <b>RATING</b> är deras rating vid ögonblicksbilden, eller Unranked.\n- <b>POOL #</b> är deras plats i kortpoolen vid ögonblicksbilden - ordningen som avgör sällsyntheten (se Player Cards). Ett lägre tal är ett sällsyntare kort.\n- <b>BOARD #</b> är deras plats på topplistan vid ögonblicksbilden: fem eller fler rankade serier och nyligen aktiv. Ett streck betyder att de inte var på listan den dagen.\n- <b>RECORD</b> är rankade serier vunna och förlorade vid ögonblicksbilden.\n\n<color=#FFD94D><b>MÄRKENA</b></color>\n\n- Ett <b>Signerat</b> kort bär spelarens autograf över bilden och ett sigill.\n- Nederkanten har utgåvan, präglingsdatumet och ditt exemplars trycknummer. Klicka på en pärmruta för att se kortet i full storlek.')
  -- "Each pack holds {0} cards. A card's rarity is its player's r"
  ,  ('83bfe0b8abeedba6', 'es', 'b6319176d253732eb634c772cac7cf0e34e3fa78', E'Cada sobre trae {0} cartas. La rareza de una carta es el puesto de su jugador en el pool de cartas el día de la tirada: Legendaria = #1-2, Épica #3-10, Rara #11-20, Poco común #21-40, Común #41 en adelante. Probabilidades por carta: Común 60%, Poco común 25%, Rara 11%, Épica 3,5%, Legendaria 0,5%. Cada carta también tira Foil (1 de cada 200) y Firmada (1 de cada 2000) por su cuenta.')
  ,  ('83bfe0b8abeedba6', 'ru', 'b6319176d253732eb634c772cac7cf0e34e3fa78', E'В каждом паке {0} карт. Редкость карты - это место её игрока в пуле карт в день вытягивания: Легендарная = #1-2, Эпическая #3-10, Редкая #11-20, Необычная #21-40, Обычная #41 и ниже. Шансы на карту: Обычная 60%, Необычная 25%, Редкая 11%, Эпическая 3,5%, Легендарная 0,5%. Каждая карта также отдельно разыгрывает признаки Фольга (1 из 200) и Подпись (1 из 2000).')
  ,  ('83bfe0b8abeedba6', 'uk', 'b6319176d253732eb634c772cac7cf0e34e3fa78', E'У кожному паку {0} карток. Рідкість картки - це місце її гравця в пулі карток у день витягування: Легендарна = #1-2, Епічна #3-10, Рідкісна #11-20, Незвичайна #21-40, Звичайна #41 і нижче. Шанси на картку: Звичайна 60%, Незвичайна 25%, Рідкісна 11%, Епічна 3,5%, Легендарна 0,5%. Кожна картка також окремо розігрує ознаки Фольга (1 із 200) і Підпис (1 із 2000).')
  ,  ('83bfe0b8abeedba6', 'sv', 'b6319176d253732eb634c772cac7cf0e34e3fa78', E'Varje paket innehåller {0} kort. Ett korts sällsynthet är dess spelares plats i kortpoolen den dag det dras: Legendarisk = #1-2, Episk #3-10, Sällsynt #11-20, Ovanlig #21-40, Vanlig #41 och nedåt. Odds per kort: Vanlig 60%, Ovanlig 25%, Sällsynt 11%, Episk 3,5%, Legendarisk 0,5%. Varje kort slår dessutom Folie (1 på 200) och Signerat (1 på 2000) för sig.')
  -- "Player Cards are collectible cards of the people who play he"
  ,  ('98a3af3eca38f474', 'es', '644f0ed2cd061e7ab4677941309c0cc9a607d8db', E'Las Player Cards son cartas coleccionables de la gente que juega aquí. Todo jugador que haya ejecutado el mod desde una cuenta de Steam y no esté baneado en ese momento tiene una carta en el pool; abres sobres, te quedas con las cartas que te gustan, descartas el resto por fragmentos y persigues las raras. Todo vive en <color=#7FD4FF>Shop > Collection</color>: <b>Open Packs</b>, <b>Binder</b> y <b>Get packs</b>.\n\n<color=#FFD94D><b>EL POOL, LAS EDICIONES Y LAS INSTANTÁNEAS</b></color>\n\n- El <b>pool</b> es cada jugador elegible, congelado en una <b>instantánea</b>: rating, historial, nivel de rango, carta top y título tal como estaban ese día. Una carta que sacas conserva esos datos como los vio la instantánea y nunca cambian después - eso es lo que hace que una carta vieja sea una carta vieja. Dos cosas de una carta siguen vivas: el nombre del jugador (un cambio de nombre se refleja) y su imagen (ver Imágenes y ajustes de las cartas).\n- Una <b>edición</b> (Ed. 1, Ed. 2 ...) es una serie de instantáneas. La edición y la fecha en que se acuñó tu carta van impresas en su borde inferior, con un número de impresión corto que es único de tu copia.\n- La línea del pool bajo los botones de sobres te dice cuántos jugadores tiene la instantánea actual y cuándo se tomó.')
  ,  ('98a3af3eca38f474', 'ru', '644f0ed2cd061e7ab4677941309c0cc9a607d8db', E'Player Cards - это коллекционные карты людей, которые здесь играют. У каждого игрока, запускавшего мод с аккаунта Steam и не забаненного в данный момент, есть карта в пуле; ты открываешь паки, оставляешь карты, которые нравятся, сбрасываешь остальные за осколки и охотишься за редкими. Всё живёт в <color=#7FD4FF>Shop > Collection</color>: <b>Open Packs</b>, <b>Binder</b> и <b>Get packs</b>.\n\n<color=#FFD94D><b>ПУЛ, ИЗДАНИЯ И СНИМКИ</b></color>\n\n- <b>Пул</b> - это все подходящие игроки, замороженные в <b>снимке</b>: рейтинг, статистика, ступень ранга, топ-карта и титул такими, какими они были в тот день. Вытянутая карта хранит их такими, какими их увидел снимок, и они больше никогда не меняются - именно это делает старую карту старой. Две вещи на карте остаются живыми: имя игрока (переименование подхватывается) и его картинка (см. Картинки и настройки карт).\n- <b>Издание</b> (Ed. 1, Ed. 2 ...) - это одна серия снимков. Издание и дата выпуска твоей карты напечатаны вдоль её нижнего края вместе с коротким номером экземпляра, уникальным для твоей копии.\n- Строка пула под кнопками паков показывает, сколько игроков в текущем снимке и когда он был сделан.')
  ,  ('98a3af3eca38f474', 'uk', '644f0ed2cd061e7ab4677941309c0cc9a607d8db', E'Player Cards - це колекційні картки людей, які тут грають. Кожен гравець, що запускав мод з акаунта Steam і не забанений на цей момент, має картку в пулі; ви відкриваєте паки, лишаєте картки, які подобаються, скидаєте решту за уламки й полюєте на рідкісні. Усе живе в <color=#7FD4FF>Shop > Collection</color>: <b>Open Packs</b>, <b>Binder</b> і <b>Get packs</b>.\n\n<color=#FFD94D><b>ПУЛ, ВИДАННЯ ТА ЗНІМКИ</b></color>\n\n- <b>Пул</b> - це всі придатні гравці, заморожені у <b>знімку</b>: рейтинг, статистика, щабель рангу, топ-картка й титул такими, якими вони були того дня. Витягнута картка зберігає їх такими, якими їх побачив знімок, і вони більше ніколи не змінюються - саме це робить стару картку старою. Дві речі на картці лишаються живими: ім''я гравця (перейменування підхоплюється) і його зображення (див. Зображення та налаштування карток).\n- <b>Видання</b> (Ed. 1, Ed. 2 ...) - це одна серія знімків. Видання й дата випуску вашої картки надруковані вздовж її нижнього краю разом із коротким номером примірника, унікальним для вашої копії.\n- Рядок пулу під кнопками паків показує, скільки гравців у поточному знімку й коли його зроблено.')
  ,  ('98a3af3eca38f474', 'sv', '644f0ed2cd061e7ab4677941309c0cc9a607d8db', E'Player Cards är samlarkort på människorna som spelar här. Varje spelare som har kört moddet från ett Steam-konto och inte är bannad just nu har ett kort i poolen; du öppnar paket, behåller korten du gillar, kastar resten för skärvor och jagar de sällsynta. Allt finns under <color=#7FD4FF>Shop > Collection</color>: <b>Open Packs</b>, <b>Binder</b> och <b>Get packs</b>.\n\n<color=#FFD94D><b>POOLEN, UTGÅVOR OCH ÖGONBLICKSBILDER</b></color>\n\n- <b>Poolen</b> är varje kvalificerad spelare, fryst i en <b>ögonblicksbild</b>: rating, facit, rangnivå, toppkort och titel som de var den dagen. Ett kort du drar behåller dem som ögonblicksbilden såg dem och de ändras aldrig efteråt - det är det som gör ett gammalt kort till ett gammalt kort. Två saker på ett kort är levande: spelarens namn (ett namnbyte följer med) och bilden (se Kortbilder & inställningar).\n- En <b>utgåva</b> (Ed. 1, Ed. 2 ...) är en omgång ögonblicksbilder. Utgåvan och datumet då ditt kort präglades är tryckta längs dess nederkant, med ett kort trycknummer som är unikt för ditt exemplar.\n- Poolraden under paketknapparna säger hur många spelare den aktuella ögonblicksbilden rymmer och när den togs.')
  -- "<color=#FFD94D><b>GETTING PACKS</b></color>  - <b>One free p"
  ,  ('cf026731cc105418', 'es', '2c525b2f5f4332ea1c5621b06fe5225ae89f84c4', E'<color=#FFD94D><b>CONSEGUIR SOBRES</b></color>\n\n- <b>Un sobre gratis al día</b> - pulsa Claim en la pestaña Open Packs o usa /daily en Discord. El día se reinicia a medianoche UTC.\n- Los <b>sobres de pago</b> cuestan 100 de oro o 100 fragmentos y traen 5 cartas. Hasta 5 sobres de pago al día para la mayoría de cuentas; la pestaña Get packs dice qué se aplica a la tuya.\n- <b>Sobres ganados</b>: ganar una serie clasificatoria, o un combate clasificatorio de FFA, da un sobre una de cada cinco veces - la misma probabilidad en 1v1, 2v2, 1v2 y FFA por igual, y el marcador no cambia nada. Los sobres ganados y reclamados esperan en <b>Packs waiting</b> hasta que los abras, todo el tiempo que quieras.\n\n<color=#FFD94D><b>QUÉ HAY EN UN SOBRE</b></color>\n\n- Cada carta tira su rareza por su cuenta: <color=#8085A0>Común 60%</color>, <color=#4DB861>Poco común 25%</color>, <color=#408CFA>Rara 11%</color>, <color=#9E52EB>Épica 3,5%</color>, <color=#FFB82E>Legendaria 0,5%</color>.\n- La rareza decide A QUIÉN te toca: el pool está ordenado (primero los jugadores que han jugado una serie clasificatoria, luego por rating), y las posiciones #1 y #2 del pool son las dos cartas Legendarias, de la #3 a la #10 son Épicas, de la #11 a la #20 Raras, de la #21 a la #40 Poco comunes, y todos los demás son Comunes.\n- Independientemente de la rareza, cualquier carta puede salir <b>Foil</b> (1 de cada 200) o <b>Firmada</b> (1 de cada 2.000) - una foil brilla, una carta firmada lleva el autógrafo del jugador.\n- La tira bajo los botones muestra tu último sobre, y los botones Anteriores / Recientes pasan por todos los sobres que has abierto. Una carta que descartaste se queda en su sobre, con el sello DESCARTADA.\n\n<color=#FFD94D><b>DUPLICADOS Y FRAGMENTOS</b></color>\n\n- Una carta que ya tienes se marca DUPLICATE al salir (+1, +2 ... según cuántas copias tenías antes).\n- <b>Discard</b> convierte una carta en fragmentos: <color=#8085A0>Común 5</color>, <color=#4DB861>Poco común 15</color>, <color=#408CFA>Rara 40</color>, <color=#9E52EB>Épica 150</color>, <color=#FFB82E>Legendaria 600</color>. Te pide pulsar dos veces. <b>Dupes</b> descarta todas las copias menos una de una sola vez.\n- Los fragmentos compran sobres al mismo precio que el oro - 100 por sobre.\n\n<color=#FFD94D><b>DISCORD</b></color>\n\n- /daily reclama el sobre gratis, /collection muestra un álbum, /card muestra una carta - todo con una cuenta de Discord vinculada.\n- Una tirada Épica o mejor se anuncia en el chat de apostadores de Discord, igual que una tirada de tu propia carta, una Foil o una Firmada de cualquier rareza - pero solo cuando TANTO tú COMO el jugador de la carta tenéis activado <b>Announce my pulls</b> (ver Imágenes y ajustes de las cartas). Una tirada Rara o inferior que no sea ninguna de esas no se anuncia.')
  ,  ('cf026731cc105418', 'ru', '2c525b2f5f4332ea1c5621b06fe5225ae89f84c4', E'<color=#FFD94D><b>КАК ПОЛУЧАТЬ ПАКИ</b></color>\n\n- <b>Один бесплатный пак в день</b> - нажми Claim на вкладке Open Packs или используй /daily в Discord. День обновляется в полночь UTC.\n- <b>Платные паки</b> стоят 100 золота или 100 осколков и содержат 5 карт. До 5 платных паков в день для большинства аккаунтов; вкладка Get packs говорит, что действует для твоего.\n- <b>Заработанные паки</b>: победа в рейтинговой серии или в рейтинговом матче FFA даёт пак в одном случае из пяти - одинаково в 1v1, 2v2, 1v2 и FFA, и счёт при этом ничего не меняет. Заработанные и полученные паки ждут в <b>Packs waiting</b>, пока ты их не откроешь, сколько угодно долго.\n\n<color=#FFD94D><b>ЧТО В ПАКЕ</b></color>\n\n- Каждая карта разыгрывает свою редкость сама по себе: <color=#8085A0>Обычная 60%</color>, <color=#4DB861>Необычная 25%</color>, <color=#408CFA>Редкая 11%</color>, <color=#9E52EB>Эпическая 3,5%</color>, <color=#FFB82E>Легендарная 0,5%</color>.\n- Редкость решает, КТО тебе достанется: пул упорядочен (сначала игроки, сыгравшие рейтинговую серию, затем по рейтингу), и позиции #1-2 в пуле - две Легендарные карты, #3-10 - Эпические, #11-20 - Редкие, #21-40 - Необычные, а все остальные - Обычные.\n- Независимо от редкости любая карта может выпасть <b>фольгированной</b> (1 из 200) или <b>подписанной</b> (1 из 2000) - фольга переливается, подписанная карта несёт автограф игрока.\n- Полоса под кнопками показывает твой последний пак, а кнопки Старее / Новее листают все паки, которые ты открыл. Сброшенная карта остаётся в своём паке со штампом СБРОШЕНА.\n\n<color=#FFD94D><b>ДУБЛИКАТЫ И ОСКОЛКИ</b></color>\n\n- Карта, которая у тебя уже есть, при выпадении помечается DUPLICATE (+1, +2 ... по числу копий, которые были у тебя до неё).\n- <b>Discard</b> превращает карту в осколки: <color=#8085A0>Обычная 5</color>, <color=#4DB861>Необычная 15</color>, <color=#408CFA>Редкая 40</color>, <color=#9E52EB>Эпическая 150</color>, <color=#FFB82E>Легендарная 600</color>. Нужно нажать дважды. <b>Dupes</b> сбрасывает все копии, кроме одной, за один раз.\n- Осколки покупают паки по той же цене, что и золото - 100 за пак.\n\n<color=#FFD94D><b>DISCORD</b></color>\n\n- /daily забирает бесплатный пак, /collection показывает альбом, /card показывает одну карту - всё при привязанном аккаунте Discord.\n- Выпадение Эпической карты или лучше объявляется в Discord-чате азартных игроков, как и выпадение твоей собственной карты, фольгированной или подписанной любой редкости - но только когда И у тебя, И у игрока на карте включено <b>Announce my pulls</b> (см. Картинки и настройки карт). Редкая или ниже, если это ничто из перечисленного, не объявляется.')
  ,  ('cf026731cc105418', 'uk', '2c525b2f5f4332ea1c5621b06fe5225ae89f84c4', E'<color=#FFD94D><b>ЯК ОТРИМУВАТИ ПАКИ</b></color>\n\n- <b>Один безкоштовний пак на день</b> - натисніть Claim на вкладці Open Packs або скористайтеся /daily у Discord. День оновлюється опівночі за UTC.\n- <b>Платні паки</b> коштують 100 золота або 100 уламків і містять 5 карток. До 5 платних паків на день для більшості акаунтів; вкладка Get packs каже, що діє для вашого.\n- <b>Зароблені паки</b>: перемога в рейтинговій серії або в рейтинговому матчі FFA дає пак в одному випадку з п''яти - однаково у 1v1, 2v2, 1v2 та FFA, і рахунок при цьому нічого не змінює. Зароблені й отримані паки чекають у <b>Packs waiting</b>, доки ви їх не відкриєте, скільки завгодно довго.\n\n<color=#FFD94D><b>ЩО В ПАКУ</b></color>\n\n- Кожна картка розігрує свою рідкість окремо: <color=#8085A0>Звичайна 60%</color>, <color=#4DB861>Незвичайна 25%</color>, <color=#408CFA>Рідкісна 11%</color>, <color=#9E52EB>Епічна 3,5%</color>, <color=#FFB82E>Легендарна 0,5%</color>.\n- Рідкість вирішує, ХТО вам дістанеться: пул упорядковано (спершу гравці, що зіграли рейтингову серію, далі за рейтингом), і позиції #1-2 у пулі - дві Легендарні картки, #3-10 - Епічні, #11-20 - Рідкісні, #21-40 - Незвичайні, а всі решта - Звичайні.\n- Незалежно від рідкості будь-яка картка може випасти <b>фольгованою</b> (1 із 200) або <b>підписаною</b> (1 із 2000) - фольга мерехтить, підписана картка несе автограф гравця.\n- Смуга під кнопками показує ваш останній пак, а кнопки Старіші / Новіші гортають усі паки, які ви відкрили. Скинута картка лишається у своєму паку зі штампом СКИНУТО.\n\n<color=#FFD94D><b>ДУБЛІКАТИ ТА УЛАМКИ</b></color>\n\n- Картка, яка у вас уже є, при випаданні позначається DUPLICATE (+1, +2 ... за кількістю копій, що були у вас до неї).\n- <b>Discard</b> перетворює картку на уламки: <color=#8085A0>Звичайна 5</color>, <color=#4DB861>Незвичайна 15</color>, <color=#408CFA>Рідкісна 40</color>, <color=#9E52EB>Епічна 150</color>, <color=#FFB82E>Легендарна 600</color>. Потрібно натиснути двічі. <b>Dupes</b> скидає всі копії, крім однієї, за один раз.\n- Уламки купують паки за тією ж ціною, що й золото - 100 за пак.\n\n<color=#FFD94D><b>DISCORD</b></color>\n\n- /daily забирає безкоштовний пак, /collection показує альбом, /card показує одну картку - усе з прив''язаним акаунтом Discord.\n- Випадання Епічної картки або кращої оголошується в Discord-чаті азартних гравців, як і випадання вашої власної картки, фольгованої чи підписаної будь-якої рідкості - але лише коли І у вас, І у гравця на картці ввімкнено <b>Announce my pulls</b> (див. Зображення та налаштування карток). Рідкісна або нижча, якщо це ніщо з переліченого, не оголошується.')
  ,  ('cf026731cc105418', 'sv', '2c525b2f5f4332ea1c5621b06fe5225ae89f84c4', E'<color=#FFD94D><b>ATT FÅ PAKET</b></color>\n\n- <b>Ett gratispaket om dagen</b> - tryck Claim på fliken Open Packs eller använd /daily i Discord. Dagen nollställs vid midnatt UTC.\n- <b>Köpta paket</b> kostar 100 guld eller 100 skärvor och rymmer 5 kort. Upp till 5 köpta paket om dagen för de flesta konton; fliken Get packs säger vad som gäller för ditt.\n- <b>Förtjänade paket</b>: en vunnen rankad serie, eller en vunnen rankad FFA-match, ger ett paket en gång på fem - samma chans i 1v1, 2v2, 1v2 och FFA, och ställningen ändrar ingenting. Förtjänade och hämtade paket väntar under <b>Packs waiting</b> tills du öppnar dem, hur länge du vill.\n\n<color=#FFD94D><b>VAD SOM FINNS I ETT PAKET</b></color>\n\n- Varje kort slår sin sällsynthet för sig: <color=#8085A0>Vanlig 60%</color>, <color=#4DB861>Ovanlig 25%</color>, <color=#408CFA>Sällsynt 11%</color>, <color=#9E52EB>Episk 3,5%</color>, <color=#FFB82E>Legendarisk 0,5%</color>.\n- Sällsyntheten avgör VEM du får: poolen är ordnad (spelare som har spelat en rankad serie först, sedan efter rating), och poolplats #1-2 är de två Legendariska korten, #3-10 är Episka, #11-20 Sällsynta, #21-40 Ovanliga, och alla därefter är Vanliga.\n- Oberoende av sällsyntheten kan vilket kort som helst komma ut som <b>Foil</b> (1 på 200) eller <b>Signerat</b> (1 på 2 000) - en foil skimrar, ett signerat kort bär spelarens autograf.\n- Remsan under knapparna visar ditt senaste paket, och knapparna Äldre / Nyare bläddrar bakåt genom varje paket du har öppnat. Ett kort du kastade stannar i sitt paket, stämplat KASTAT.\n\n<color=#FFD94D><b>DUBBLETTER OCH SKÄRVOR</b></color>\n\n- Ett kort du redan äger märks DUPLICATE när det landar (+1, +2 ... för hur många exemplar du hade innan det).\n- <b>Discard</b> gör om ett kort till skärvor: <color=#8085A0>Vanlig 5</color>, <color=#4DB861>Ovanlig 15</color>, <color=#408CFA>Sällsynt 40</color>, <color=#9E52EB>Episk 150</color>, <color=#FFB82E>Legendarisk 600</color>. Den ber dig klicka två gånger. <b>Dupes</b> kastar varje exemplar utom ett i ett svep.\n- Skärvor köper paket till samma pris som guld - 100 för ett paket.\n\n<color=#FFD94D><b>DISCORD</b></color>\n\n- /daily hämtar gratispaketet, /collection visar en pärm, /card visar ett kort - allt med ett länkat Discord-konto.\n- En dragning som är Episk eller bättre meddelas i Discords gambler-chatt, och det gör även en dragning av ditt eget kort, en Foil eller ett Signerat tryck oavsett sällsynthet - men bara när BÅDE du och spelaren på kortet har <b>Announce my pulls</b> på (se Kortbilder & inställningar). En Sällsynt eller lägre dragning som inte är någon av dessa meddelas inte.')
  -- "<color=#FFD94D><b>YOUR PICTURE ON OTHER PEOPLE'S CARDS</b></"
  ,  ('d09d8f0a4703b058', 'es', '5d63ac2019950a3b867b48ff90c6b381999c6878', E'<color=#FFD94D><b>TU IMAGEN EN LAS CARTAS DE LOS DEMÁS</b></color>\n\n- Tu carta muestra tu <b>personaje del juego</b>: el cuerpo, los objetos de la cara, el color y el efecto con los que juegas, dibujado por tu propio PC cuando visitas la pestaña Collection o Settings tras un cambio, y enviado una sola vez. Ningún otro PC te renderiza.\n- Antes de que tu PC lo haya enviado, tu carta muestra tu <b>imagen de perfil de Steam</b>, que el servidor toma de tu perfil público.\n- La imagen no es un ajuste: toda carta de ti muestra tu imagen de Steam hasta que tu PC haya enviado el personaje, y después el personaje - incluidas las cartas sacadas antes de enviarlo. El personaje que envió tu PC sigue guardado hasta que envíes otro.\n- <b>Character preset</b> elige qué personaje guardado muestra tu imagen: Follow usa el que tienes seleccionado en el menú de personaje, o fija un preset. La pequeña vista previa de debajo es lo que muestra tu carta.\n\n<color=#FFD94D><b>LOS OTROS AJUSTES</b></color>\n\n- No hay exclusión: todo jugador que haya ejecutado el mod desde una cuenta de Steam y no esté baneado está en el pool, y las cartas de ti se quedan en los álbumes que las tienen.\n- <b>Public collection</b> es el ajuste que muestra u oculta tu álbum a los demás (/collection en Discord).\n- <b>Announce my pulls</b> permite publicaciones en Discord sobre tus tiradas Épicas o mejores, Foil y Firmadas, y sobre las tiradas de TU carta - ambas partes deben tenerlo activado para que haya publicación.\n- Borrar tus datos es lo que elimina cartas: tu álbum se vacía y toda carta de ti se retira del álbum de cualquier otro jugador.\n\n<color=#FFD94D><b>POR QUÉ UNA CARTA MUESTRA LO QUE MUESTRA</b></color>\n\n- El rating, el historial, el nivel de rango y el título de la tienda de una carta se congelan en la instantánea de la que se acuñó. Si mañana subes de rango, las cartas de ti acuñadas hoy conservan el rango de hoy; las cartas de la siguiente instantánea reciben el nuevo.\n- El nombre y la imagen están vivos: una carta de un jugador renombrado muestra el nuevo nombre, y su imagen sigue lo último que envió el PC de ese jugador (o su imagen de Steam hasta entonces).\n- Si el jugador borra sus datos, todas sus cartas se retiran de todos los álbumes.')
  ,  ('d09d8f0a4703b058', 'ru', '5d63ac2019950a3b867b48ff90c6b381999c6878', E'<color=#FFD94D><b>ТВОЯ КАРТИНКА НА ЧУЖИХ КАРТАХ</b></color>\n\n- Карта с тобой показывает твоего <b>игрового персонажа</b>: тело, предметы на лице, цвет и эффект, с которыми ты играешь, нарисованные твоим собственным ПК при заходе на вкладку Collection или Settings после изменения и отправленные один раз. Ничей другой ПК тебя не рисует.\n- Пока твой ПК их не отправил, карта показывает твою <b>картинку профиля Steam</b>, которую сервер берёт из твоего публичного профиля.\n- Картинка - не настройка: каждая карта с тобой показывает твою картинку Steam, пока твой ПК не отправил персонажа, а затем персонажа - включая карты, выпавшие до отправки. Персонаж, отправленный твоим ПК, остаётся сохранённым, пока ты не отправишь другого.\n- <b>Character preset</b> выбирает, какого сохранённого персонажа показывает картинка: Follow берёт того, кто выбран в меню персонажа, либо закрепи пресет. Маленький предпросмотр под ним - это то, что показывает твоя карта.\n\n<color=#FFD94D><b>ОСТАЛЬНЫЕ НАСТРОЙКИ</b></color>\n\n- Отказаться от участия нельзя: каждый незабаненный игрок, запускавший мод с аккаунта Steam, находится в пуле, а карты с тобой остаются в альбомах, где они лежат.\n- <b>Public collection</b> - настройка, которая показывает или скрывает твой альбом от других (/collection в Discord).\n- <b>Announce my pulls</b> разрешает посты в Discord о твоих выпадениях Эпических или лучше, фольгированных и подписанных, а также о выпадениях ТВОЕЙ карты - для поста она должна быть включена у обеих сторон.\n- Удаление данных - вот что убирает карты: твой альбом опустошается, и каждая карта с тобой убирается из альбомов всех остальных игроков.\n\n<color=#FFD94D><b>ПОЧЕМУ КАРТА ПОКАЗЫВАЕТ ТО, ЧТО ПОКАЗЫВАЕТ</b></color>\n\n- Рейтинг, статистика, ступень ранга и титул из магазина на карте заморожены на момент снимка, из которого она выпущена. Если завтра ты поднимешься в ранге, карты с тобой, выпущенные сегодня, сохранят сегодняшний ранг; карты следующего снимка получат новый.\n- Имя и картинка живые: карта переименованного игрока показывает новое имя, а её картинка следует за тем, что ПК этого игрока отправил последним (или за его картинкой Steam до тех пор).\n- Если игрок удалил свои данные, все карты с ним убираются из всех альбомов.')
  ,  ('d09d8f0a4703b058', 'uk', '5d63ac2019950a3b867b48ff90c6b381999c6878', E'<color=#FFD94D><b>ВАШЕ ЗОБРАЖЕННЯ НА ЧУЖИХ КАРТКАХ</b></color>\n\n- Картка з вами показує вашого <b>ігрового персонажа</b>: тіло, предмети на обличчі, колір і ефект, з якими ви граєте, намальовані вашим власним ПК під час заходу на вкладку Collection або Settings після зміни й надіслані один раз. Нічий інший ПК вас не малює.\n- Поки ваш ПК їх не надіслав, картка показує ваше <b>зображення профілю Steam</b>, яке сервер бере з вашого публічного профілю.\n- Зображення - не налаштування: кожна картка з вами показує ваше зображення Steam, доки ваш ПК не надіслав персонажа, а потім персонажа - включно з картками, що випали до надсилання. Персонаж, надісланий вашим ПК, лишається збереженим, доки ви не надішлете іншого.\n- <b>Character preset</b> вибирає, якого збереженого персонажа показує зображення: Follow бере того, кого вибрано в меню персонажа, або закріпіть пресет. Маленький передперегляд під ним - це те, що показує ваша картка.\n\n<color=#FFD94D><b>РЕШТА НАЛАШТУВАНЬ</b></color>\n\n- Відмовитися від участі не можна: кожен незабанений гравець, що запускав мод з акаунта Steam, є в пулі, а картки з вами лишаються в альбомах, де вони лежать.\n- <b>Public collection</b> - налаштування, яке показує або ховає ваш альбом від інших (/collection у Discord).\n- <b>Announce my pulls</b> дозволяє дописи в Discord про ваші випадання Епічних або кращих, фольгованих і підписаних, а також про випадання ВАШОЇ картки - для допису воно має бути ввімкнене в обох сторін.\n- Видалення даних - ось що прибирає картки: ваш альбом спорожнюється, і кожна картка з вами прибирається з альбомів усіх інших гравців.\n\n<color=#FFD94D><b>ЧОМУ КАРТКА ПОКАЗУЄ ТЕ, ЩО ПОКАЗУЄ</b></color>\n\n- Рейтинг, статистика, щабель рангу й титул із крамниці на картці заморожені на момент знімка, з якого її випущено. Якщо завтра ви піднімете ранг, картки з вами, випущені сьогодні, збережуть сьогоднішній ранг; картки наступного знімка отримають новий.\n- Ім''я та зображення живі: картка перейменованого гравця показує нове ім''я, а її зображення йде за тим, що ПК цього гравця надіслав останнім (або за його зображенням Steam до того).\n- Якщо гравець видалив свої дані, усі картки з ним прибираються з усіх альбомів.')
  ,  ('d09d8f0a4703b058', 'sv', '5d63ac2019950a3b867b48ff90c6b381999c6878', E'<color=#FFD94D><b>DIN BILD PÅ ANDRAS KORT</b></color>\n\n- Kortet av dig visar din <b>spelfigur</b>: kroppen, ansiktsföremålen, färgen och effekten du spelar med, ritad av din egen dator när du besöker fliken Collection eller Settings efter en ändring, och skickad en gång. Ingen annans dator ritar dig.\n- Innan din dator har skickat den visar ditt kort din <b>Steam-profilbild</b>, som servern hämtar från din offentliga profil.\n- Bilden är ingen inställning: varje kort av dig visar din Steam-bild tills din dator har skickat figuren, och sedan figuren - även kort som drogs innan den skickades. Figuren din dator skickade förblir lagrad tills du skickar en annan.\n- <b>Character preset</b> väljer vilken sparad figur din bild visar: Follow använder den du har vald i figurmenyn, eller fäst en förinställning. Den lilla förhandsvisningen under är det som ditt kort visar.\n\n<color=#FFD94D><b>DE ANDRA INSTÄLLNINGARNA</b></color>\n\n- Det går inte att välja bort: varje spelare som har kört moddet från ett Steam-konto och inte är bannad finns i poolen, och kort av dig stannar i de pärmar som har dem.\n- <b>Public collection</b> är inställningen som visar eller döljer din pärm för andra (/collection i Discord).\n- <b>Announce my pulls</b> tillåter Discord-inlägg om dina Episka-eller-bättre-, Foil- och Signerade dragningar, och om dragningar av DITT kort - båda sidor måste ha det på för att ett inlägg ska ske.\n- Att radera dina data är det som tar bort kort: din pärm töms, och varje kort av dig tas bort ur alla andra spelares pärmar.\n\n<color=#FFD94D><b>VARFÖR ETT KORT VISAR DET DET VISAR</b></color>\n\n- Ett korts rating, facit, rangnivå och butikstitel fryses vid ögonblicksbilden det präglades från. Om du går upp i rang i morgon behåller kort av dig som präglades i dag dagens rang; nästa ögonblicksbilds kort får den nya.\n- Namnet och bilden är levande: ett kort av en omdöpt spelare visar det nya namnet, och dess bild följer det som den spelarens dator senast skickade (eller deras Steam-bild fram till dess).\n- Om spelaren raderar sina data tas alla kort av dem bort ur alla pärmar.')
  -- "Too many requests at once - wait a few seconds and try again"
  ,  ('e224785f648cafd4', 'es', '27c832cb50f6c0ab3338996d8ebb7bd1bf16fc73', E'Demasiadas solicitudes a la vez - espera unos segundos y vuelve a intentarlo')
  ,  ('e224785f648cafd4', 'ru', '27c832cb50f6c0ab3338996d8ebb7bd1bf16fc73', E'Слишком много запросов сразу - подожди несколько секунд и попробуй снова')
  ,  ('e224785f648cafd4', 'uk', '27c832cb50f6c0ab3338996d8ebb7bd1bf16fc73', E'Забагато запитів одразу - зачекайте кілька секунд і спробуйте ще раз')
  ,  ('e224785f648cafd4', 'sv', '27c832cb50f6c0ab3338996d8ebb7bd1bf16fc73', E'För många förfrågningar på en gång - vänta några sekunder och försök igen')
  -- "- Ranked wins: winning a ranked series - or a ranked FFA mat"
  ,  ('f9786e977e586b20', 'es', 'a1839d0465cd99b62e5ca6de094399aa18d2c159', E'- Victorias clasificatorias: ganar una serie clasificatoria - o un combate clasificatorio de FFA - tira un 20% de probabilidad de sobre. La misma probabilidad en todos los modos, sea cual sea el marcador. Los sobres ganados esperan aquí hasta que los abras.')
  ,  ('f9786e977e586b20', 'ru', 'a1839d0465cd99b62e5ca6de094399aa18d2c159', E'- Рейтинговые победы: победа в рейтинговой серии - или в рейтинговом матче FFA - разыгрывает шанс пака 20%. Одинаково во всех режимах, каким бы ни был счёт. Заработанные паки ждут здесь, пока ты их не откроешь.')
  ,  ('f9786e977e586b20', 'uk', 'a1839d0465cd99b62e5ca6de094399aa18d2c159', E'- Рейтингові перемоги: перемога в рейтинговій серії - або в рейтинговому матчі FFA - розігрує шанс паку 20%. Однаково в усіх режимах, яким би не був рахунок. Зароблені паки чекають тут, доки ви їх не відкриєте.')
  ,  ('f9786e977e586b20', 'sv', 'a1839d0465cd99b62e5ca6de094399aa18d2c159', E'- Rankade vinster: en vunnen rankad serie - eller en vunnen rankad FFA-match - slår en 20% chans på ett paket. Samma chans i alla lägen, oavsett ställning. Förtjänade paket väntar här tills du öppnar dem.')
  -- "A card freezes its player's title, rating, record and rank a"
  ,  ('fd240ccd9449ca74', 'es', '5688b1c7c63a79869d3d5a88ecffc466c9e35bf1', E'Una carta congela el título, el rating, el historial y el rango de su jugador tal como los tenía la clasificación el día en que salió; el nombre y la imagen siguen vivos (un jugador renombrado muestra su nuevo nombre). Todo jugador que haya ejecutado el mod desde una cuenta de Steam y no esté baneado puede salir en un sobre; un álbum público y los anuncios de tiradas son tus Ajustes, y borrar tus datos quita toda carta de ti de todos los álbumes.')
  ,  ('fd240ccd9449ca74', 'ru', '5688b1c7c63a79869d3d5a88ecffc466c9e35bf1', E'Карта замораживает титул, рейтинг, статистику и ранг своего игрока такими, какими они были в таблице лидеров в день, когда её вытянули; имя и картинка остаются живыми (переименованный игрок показывает новое имя). Вытянуть можно любого незабаненного игрока, запускавшего мод с аккаунта Steam; публичный альбом и объявления о вытянутых картах - твои настройки, а удаление твоих данных убирает каждую карту с тобой из всех альбомов.')
  ,  ('fd240ccd9449ca74', 'uk', '5688b1c7c63a79869d3d5a88ecffc466c9e35bf1', E'Картка заморожує титул, рейтинг, статистику та ранг свого гравця такими, якими їх мала таблиця лідерів у день, коли її витягли; ім''я та зображення лишаються живими (перейменований гравець показує нове ім''я). Витягти можна будь-якого незабаненого гравця, що запускав мод з акаунта Steam; публічний альбом і оголошення про витягнуті картки - ваші налаштування, а видалення ваших даних прибирає кожну картку з вами з усіх альбомів.')
  ,  ('fd240ccd9449ca74', 'sv', '5688b1c7c63a79869d3d5a88ecffc466c9e35bf1', E'Ett kort fryser spelarens titel, rating, facit och rang som topplistan hade dem den dag det drogs; namnet och bilden är levande (en omdöpt spelare visar sitt nya namn). Varje spelare som har kört moddet från ett Steam-konto och inte är bannad kan dras; en offentlig pärm och dragningsmeddelanden är dina Inställningar, och att radera dina data tar bort varje kort av dig ur alla pärmar.')
;

INSERT INTO i18n_proposals
  (key_id, language_code, source_hash, proposed_target, proposer_steam_id,
   license_assent, license_terms_rev, assented_at, status, created_at)
SELECT v.key_id, v.lang, v.source_hash, v.target, 'claude-mt',
       TRUE, 'machine-v1', NOW(), 'pending', NOW()
  FROM _seed318 v
  JOIN i18n_keys k ON k.key_id = v.key_id AND k.retired_at IS NULL
                  AND k.source_hash = v.source_hash
 WHERE NOT EXISTS (
   SELECT 1 FROM i18n_proposals p
    WHERE p.key_id = v.key_id AND p.language_code = v.lang
      AND p.status = 'pending')
   AND NOT EXISTS (
   SELECT 1 FROM i18n_proposals p2
    WHERE p2.key_id = v.key_id AND p2.language_code = v.lang
      AND p2.proposer_steam_id = 'claude-mt'
      AND p2.source_hash = v.source_hash);

DO $$
DECLARE
  uncovered INTEGER;
  sample TEXT;
BEGIN
  SELECT COUNT(*) INTO uncovered
    FROM _seed318 v
   WHERE NOT EXISTS (
           SELECT 1 FROM i18n_proposals p
            WHERE p.key_id = v.key_id AND p.language_code = v.lang
              AND (p.source_hash = v.source_hash OR p.status = 'pending'))
     AND NOT EXISTS (
           SELECT 1 FROM i18n_entries e
            WHERE e.key_id = v.key_id AND e.language_code = v.lang
              AND e.state = 'approved');
  IF uncovered <> 0 THEN
    SELECT string_agg(x.key_id || '/' || x.lang, ', ')
      INTO sample
      FROM (SELECT v.key_id, v.lang FROM _seed318 v
             WHERE NOT EXISTS (
                     SELECT 1 FROM i18n_proposals p
                      WHERE p.key_id = v.key_id AND p.language_code = v.lang
                        AND (p.source_hash = v.source_hash OR p.status = 'pending'))
               AND NOT EXISTS (
                     SELECT 1 FROM i18n_entries e
                      WHERE e.key_id = v.key_id AND e.language_code = v.lang
                        AND e.state = 'approved')
             LIMIT 5) x;
    RAISE EXCEPTION 'migration 318: % of 36 seed pairs did not land (e.g. %) - the usual cause is that 317 / tools/i18n_sync_keys.py has not run against this database yet; nothing committed', uncovered, sample;
  END IF;

  RAISE NOTICE 'migration 318: all 36 seed pairs covered (9 keys x es/ru/uk/sv)';
END $$;

COMMIT;
