-- 333_pc_card_themes.sql
--
-- The colour ROUNDS itself draws each card in, seeded so the player-card
-- renderer can ink a print's top_card badge with the card's own theme instead
-- of the rarity band it falls back to today.
--
-- Generated by tools/rounds_card_themes.py --emit-sql. Re-run that
-- tool after a ROUNDS update and regenerate; it re-derives every value from
-- the installed assets and refuses to emit anything if a self-check fails.
--
-- PROVENANCE -- TWO READS, BOTH OUT OF THE SHIPPED ASSETS
-- -------------------------------------------------------
-- A decompile shows a MonoBehaviour's C# field DEFAULTS, not what the prefab
-- ships (learning #579), so neither number below comes from source.
--
--   1. THE THEME TABLE. CardChoice, level0 path_id 3810. The nine themes are
--      an INLINE struct array at the TAIL of that MonoBehaviour -- a 4-byte
--      count then count * 36 bytes of {themeType int32, targetColor RGBA
--      floats, bgColor RGBA floats}. There is no standalone CardThemeColor
--      asset anywhere in the game; looking for one is how this read gets
--      mis-designed. CardChoice.GetCardColor() is the accessor the game uses
--      for that same field, so targetColor is the colour the card is drawn
--      with rather than a colour near it.
--
--   2. CARD -> THEME. All 67 CardInfo MonoBehaviours in sharedassets0.assets.
--      The asset name is m_GameObject.deref().read().m_Name; colorTheme is the
--      int32 at offset len(raw) - 12.
--
-- THE REJECTED OFFSET
-- -------------------
-- len(raw) - 4 reads 0 -- DestructiveRed -- for all 67 cards. The CardInfo
-- decompile puts colorTheme last, so that offset looks correct and is not: the
-- shipped serialisation carries eight further bytes after the field. Had it
-- been used, every card would have been seeded the same red and the table
-- would have looked fully populated. A reading that cannot vary is not a
-- reading, so the offset sweep is part of every run of the tool, not a thing
-- done once: it asserts the accepted offset spans the whole enum 0..8 across
-- the card set and that the rejected one is still constant.
--
-- CONTROLS, RUN BEFORE ANY VALUE HERE WAS TRUSTED
-- -----------------------------------------------
--   * Migration 221's two recorded colours reproduce byte for byte:
--     A_Poison #4AD652 and A_Parasite #9E79FF. Those are RayHitPoison.color --
--     a different component, a different offset, a different read -- so they
--     test the raw-MonoBehaviour parsing without testing the theme numbers.
--   * Demonic Pact reads themeType 4 = EvilPurple = #7A50D1, which is the
--     value migration 337 traced end to end for its body colour.
--   * The four theme colours 337's header recorded are re-derived here:
--     DestructiveRed #CC4646, PoisonGreen #00934C, MagicPink #D15088,
--     EvilPurple #7A50D1.
--
-- THE CANONICAL-NAME PASS
-- -----------------------
-- card_name is NOT the asset name. The assets hold GameObject spellings
-- ("Poison bullets", "Leach", "Riccochet", "BombsAway"); pc_prints.top_card
-- holds what the client's CardRarityLookup.GetCanonicalName produces
-- ("Poison", "Leech", "Ricochet", "Bombs Away"). The generator ports that
-- function -- hardAliases, the canonical map ScanAll builds from each card's
-- serialized cardName, and ToTitleCase -- and applies it to every asset name.
-- 31 of the 67 names change. Seeding asset names instead would have produced
-- a table of 67 rows that joined on nothing for those cards, and the renderer
-- would have fallen back to the rarity band, which is exactly what "no theme"
-- looks like -- so nothing would ever have reported it. The post-check below
-- therefore asserts the canonical spellings by name.
--
-- Two of the canonical spellings are not the obvious ones, and both are what
-- the client actually writes: the "Fast ball" asset canonicalises to
-- "Fastball" (its serialized cardName is FASTBALL, and the hardAliases entry
-- pointing at "Fast Ball" never reaches that spelling), and "EMP"
-- canonicalises to "Emp", because ToTitleCase lowercases before it capitalises.
--
-- THE CONTRAST LIFT
-- -----------------
-- source_hex is the game's targetColor, unmodified, so a later pass can always
-- get back to what ROUNDS draws. hex is the ink, which has to stay legible on
-- the #12141A badge: WCAG contrast ratio >= 4.5, from sRGB relative
-- luminance, measured on the rounded 8-bit colour rather than the float.
-- Two of the nine needed lifting, by the smallest 1% step toward white that
-- clears the floor:
--     DestructiveRed  #CC4646 -> #D15757   CR 3.97 -> 4.57   (9% toward white)
--     EvilPurple      #7A50D1 -> #8E6AD8   CR 3.42 -> 4.56   (15% toward white)
-- The other seven are untouched (CR against the badge, ascending):
--     MagicPink       #D15088   CR 4.57
--     PoisonGreen     #00934C   CR 4.63
--     DefensiveBlue   #5083D1   CR 4.83
--     TechWhite       #ADADAD   CR 8.20
--     ColdBlue        #50BCD1   CR 8.29
--     FirepowerYellow #CABB3A   CR 9.36
--     NatureBrown     #92CC20   CR 9.54
--
-- DEPLOY ORDER: THIS FILE FIRST, THE API SECOND.
-- -----------------------------------------------
-- The new api QUERIES THIS TABLE AT STARTUP. `lifespan` awaits
-- `_pc_load_card_themes`, on BOTH roles and before it yields, so a box that
-- boots the new code against a database without `pc_card_themes` fails that
-- read on the boot path rather than on the first face request. The reverse
-- order is entirely safe and is the state the two-SHA order passes through:
-- the OLD api does not know this table exists, the schema is purely additive,
-- and an unread table costs nothing.
--
-- Explicit transaction: the deploy wrapper invokes `psql -f`, which does NOT
-- wrap a file in one (#340) -- every statement would otherwise autocommit and
-- a failed post-check would report a failed deploy over already-committed
-- data. Idempotent statement by statement -- and that is asserted rather than
-- asserted-and-hoped: the INSERT's `DO UPDATE` carries a `WHERE` so an
-- unchanged row is not rewritten and its `seeded_at` is not reset, which is
-- what "a re-run changes nothing" has to mean if it is to mean anything. The
-- post-check asserts the END STATE rather than trusting that the INSERT is
-- what produced it.

BEGIN;

CREATE TABLE IF NOT EXISTS pc_card_themes (
    card_name  TEXT PRIMARY KEY,
    theme      TEXT NOT NULL,
    hex        TEXT NOT NULL,
    source_hex TEXT NOT NULL,
    seeded_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO pc_card_themes (card_name, theme, hex, source_hex) VALUES
    ('Abyssal Countdown', 'EvilPurple', '#8E6AD8', '#7A50D1'),
    ('Barrage', 'FirepowerYellow', '#CABB3A', '#CABB3A'),
    ('Big Bullet', 'FirepowerYellow', '#CABB3A', '#CABB3A'),
    ('Bombs Away', 'DestructiveRed', '#D15757', '#CC4646'),
    ('Bouncy', 'DestructiveRed', '#D15757', '#CC4646'),
    ('Brawler', 'DefensiveBlue', '#5083D1', '#5083D1'),
    ('Buckshot', 'DestructiveRed', '#D15757', '#CC4646'),
    ('Burst', 'FirepowerYellow', '#CABB3A', '#CABB3A'),
    ('Careful Planning', 'FirepowerYellow', '#CABB3A', '#CABB3A'),
    ('Chase', 'DestructiveRed', '#D15757', '#CC4646'),
    ('Chilling Presence', 'ColdBlue', '#50BCD1', '#50BCD1'),
    ('Cold Bullets', 'ColdBlue', '#50BCD1', '#50BCD1'),
    ('Combine', 'FirepowerYellow', '#CABB3A', '#CABB3A'),
    ('Dazzle', 'MagicPink', '#D15088', '#D15088'),
    ('Decay', 'EvilPurple', '#8E6AD8', '#7A50D1'),
    ('Defender', 'DefensiveBlue', '#5083D1', '#5083D1'),
    ('Demonic Pact', 'EvilPurple', '#8E6AD8', '#7A50D1'),
    ('Drill Ammo', 'FirepowerYellow', '#CABB3A', '#CABB3A'),
    ('Echo', 'DestructiveRed', '#D15757', '#CC4646'),
    ('Emp', 'TechWhite', '#ADADAD', '#ADADAD'),
    ('Empower', 'TechWhite', '#ADADAD', '#ADADAD'),
    ('Explosive Bullet', 'DestructiveRed', '#D15757', '#CC4646'),
    ('Fast Forward', 'FirepowerYellow', '#CABB3A', '#CABB3A'),
    ('Fastball', 'FirepowerYellow', '#CABB3A', '#CABB3A'),
    ('Frost Slam', 'ColdBlue', '#50BCD1', '#50BCD1'),
    ('Glass Cannon', 'FirepowerYellow', '#CABB3A', '#CABB3A'),
    ('Grow', 'FirepowerYellow', '#CABB3A', '#CABB3A'),
    ('Healing Field', 'NatureBrown', '#92CC20', '#92CC20'),
    ('Homing', 'TechWhite', '#ADADAD', '#ADADAD'),
    ('Huge', 'DefensiveBlue', '#5083D1', '#5083D1'),
    ('Implode', 'TechWhite', '#ADADAD', '#ADADAD'),
    ('Leech', 'DefensiveBlue', '#5083D1', '#5083D1'),
    ('Lifestealer', 'EvilPurple', '#8E6AD8', '#7A50D1'),
    ('Mayhem', 'DestructiveRed', '#D15757', '#CC4646'),
    ('Overpower', 'DestructiveRed', '#D15757', '#CC4646'),
    ('Parasite', 'EvilPurple', '#8E6AD8', '#7A50D1'),
    ('Phoenix', 'DefensiveBlue', '#5083D1', '#5083D1'),
    ('Poison', 'PoisonGreen', '#00934C', '#00934C'),
    ('Pristine Perseverance', 'DefensiveBlue', '#5083D1', '#5083D1'),
    ('Quick Reload', 'FirepowerYellow', '#CABB3A', '#CABB3A'),
    ('Quick Shot', 'FirepowerYellow', '#CABB3A', '#CABB3A'),
    ('Radar Shot', 'TechWhite', '#ADADAD', '#ADADAD'),
    ('Radiance', 'DestructiveRed', '#D15757', '#CC4646'),
    ('Refresh', 'TechWhite', '#ADADAD', '#ADADAD'),
    ('Remote', 'TechWhite', '#ADADAD', '#ADADAD'),
    ('Ricochet', 'FirepowerYellow', '#CABB3A', '#CABB3A'),
    ('Saw', 'DestructiveRed', '#D15757', '#CC4646'),
    ('Scavenger', 'EvilPurple', '#8E6AD8', '#7A50D1'),
    ('Shield Charge', 'DefensiveBlue', '#5083D1', '#5083D1'),
    ('Shields Up', 'DefensiveBlue', '#5083D1', '#5083D1'),
    ('Shockwave', 'TechWhite', '#ADADAD', '#ADADAD'),
    ('Silence', 'MagicPink', '#D15088', '#D15088'),
    ('Sneaky', 'TechWhite', '#ADADAD', '#ADADAD'),
    ('Spray', 'FirepowerYellow', '#CABB3A', '#CABB3A'),
    ('Static Field', 'ColdBlue', '#50BCD1', '#50BCD1'),
    ('Steady Shot', 'FirepowerYellow', '#CABB3A', '#CABB3A'),
    ('Supernova', 'DestructiveRed', '#D15757', '#CC4646'),
    ('Tactical Reload', 'TechWhite', '#ADADAD', '#ADADAD'),
    ('Tank', 'DefensiveBlue', '#5083D1', '#5083D1'),
    ('Target Bounce', 'TechWhite', '#ADADAD', '#ADADAD'),
    ('Taste Of Blood', 'DestructiveRed', '#D15757', '#CC4646'),
    ('Teleport', 'DestructiveRed', '#D15757', '#CC4646'),
    ('Thruster', 'TechWhite', '#ADADAD', '#ADADAD'),
    ('Timed Detonation', 'DestructiveRed', '#D15757', '#CC4646'),
    ('Toxic Cloud', 'PoisonGreen', '#00934C', '#00934C'),
    ('Trickster', 'DestructiveRed', '#D15757', '#CC4646'),
    ('Wind Up', 'FirepowerYellow', '#CABB3A', '#CABB3A')
-- DO UPDATE ... WHERE, and the WHERE is what makes a re-run a no-op. Without
-- it, every re-run rewrote all 67 rows and reset all 67 `seeded_at` values to
-- now() -- which contradicted this file's own idempotence claim and destroyed
-- the one thing that column exists to carry: WHEN a colour was last actually
-- derived from the assets. `IS DISTINCT FROM` over the row constructors, so a
-- NULL on either side compares as a value instead of swallowing the test.
--
-- The DO UPDATE itself stays, because regenerating after a ROUNDS update is
-- the documented way a changed colour reaches this table. On such a run only
-- the rows that actually changed are written, and only those take a fresh
-- seeded_at -- which is the difference between "somebody re-ran the seed" and
-- "three cards changed colour", and the second is what a reader of seeded_at
-- is asking.
ON CONFLICT (card_name) DO UPDATE
    SET theme      = EXCLUDED.theme,
        hex        = EXCLUDED.hex,
        source_hex = EXCLUDED.source_hex,
        seeded_at  = now()
  WHERE (pc_card_themes.theme, pc_card_themes.hex, pc_card_themes.source_hex)
        IS DISTINCT FROM
        (EXCLUDED.theme, EXCLUDED.hex, EXCLUDED.source_hex);

DO $$
DECLARE
    v_rows    INTEGER;
    v_themes  INTEGER;
    v_missing TEXT[];
    v_hex     TEXT;
    v_orphans INTEGER;
BEGIN
    SELECT count(*) INTO v_rows FROM pc_card_themes;
    IF v_rows <> 67 THEN
        RAISE EXCEPTION 'pc_card_themes holds % rows, expected 67', v_rows;
    END IF;

    -- A collapsed theme column is precisely the len-4 failure described above:
    -- 67 rows, every one of them DestructiveRed, and nothing else to notice.
    SELECT count(DISTINCT theme) INTO v_themes FROM pc_card_themes;
    IF v_themes <> 9 THEN
        RAISE EXCEPTION
            'pc_card_themes spans % distinct themes, expected 9 -- a collapsed '
            'theme column is what reading colorTheme at the wrong offset looks like',
            v_themes;
    END IF;

    -- These four spellings exist only if the canonical pass ran. Their asset
    -- names are "Poison bullets", "Leach", "Riccochet" and "BombsAway".
    SELECT array_agg(n ORDER BY n) INTO v_missing
      FROM unnest(ARRAY['Poison', 'Leech', 'Ricochet', 'Bombs Away']) AS n
     WHERE NOT EXISTS (SELECT 1 FROM pc_card_themes t WHERE t.card_name = n);
    IF v_missing IS NOT NULL THEN
        RAISE EXCEPTION
            'canonical card names missing from pc_card_themes: % -- the seed '
            'was keyed on asset names, and every aliased card would silently '
            'render with its rarity band instead of its theme',
            array_to_string(v_missing, ', ');
    END IF;

    SELECT hex INTO v_hex FROM pc_card_themes WHERE card_name = 'Poison';
    IF v_hex <> '#00934C' THEN
        RAISE EXCEPTION 'Poison ink is %, expected #00934C (PoisonGreen, '
                        'which clears the contrast floor untouched)', v_hex;
    END IF;

    -- How many card names players actually hold have no theme row, i.e. how
    -- many prints still fall back to the rarity band. Modded and renamed cards
    -- land here. Guarded so the file also runs on a bare database.
    IF to_regclass('public.pc_prints') IS NOT NULL THEN
        EXECUTE $q$
            SELECT count(*) FROM (
                SELECT DISTINCT p.top_card
                  FROM pc_prints p
                 WHERE p.top_card IS NOT NULL
                   AND NOT EXISTS (SELECT 1 FROM pc_card_themes t
                                    WHERE t.card_name = p.top_card)
            ) q
        $q$ INTO v_orphans;
        RAISE NOTICE 'post-check OK: % rows, % themes; % distinct pc_prints.top_card '
                     'values have no theme row (band-colour fallback)',
                     v_rows, v_themes, v_orphans;
    ELSE
        RAISE NOTICE 'post-check OK: % rows, % themes; pc_prints absent, '
                     'fallback census skipped', v_rows, v_themes;
    END IF;
END $$;

COMMIT;
