"""The mutation controls of the release-train lane: rounds 2 to 12, one list.

Each row is (id, what the mutation removes, the test that must go RED, the
exact text replaced, its replacement). The text is a fragment of the train as
it stands at this round's tip; `train_mutations.py --anchors` checks that every
fragment is present exactly once and that each mutant and its inert twin compile.
Generated once from the round-9 harness and the round-10 additions; edited by
hand from here on, like any other source file.

Round 11 RETIRED five rows, because the code they mutated is gone: R7-L1, R6-L2,
R5-L2, R4-L5 and R8-L1 each removed one bound on the capture FILE (a link count
that fails open, a link count asked of the name, containment of the parent, a
destination taken as given, a copy instead of a rename). B11 (round 11) removed
the file itself -- the capture is printed and nothing is written -- so there is
no site left for them to edit. Their replacement is R11-B11a-c, whose test
spies on every primitive that can write.

Round 12 RE-ANCHORED one row and ADDED six. R10-M1d edited the removal that
followed the playbook (`exit $__scr_rc`); R11-L2 removed that removal with the
temporary playbook it cleaned up, so the row now appends a command after the
invocation instead -- the same property (the controller's shell exits with the
playbook's own status) at the line that now carries it. R12-M1a-e are R11-M1
(a listing is read by pct's NAME FIELD) and R12-L2a is R11-L2 (the playbook
reaches the controller as a pipe, never as a file)."""

CONTROLS = [
    ('R7-H2a',
     "the door goes back to READING THE SEAT on every line, so a seat edited after a command was composed puts today's value into yesterday's line and the value the line actually carried is the one that survives",
     'test_every_line_this_train_prints_goes_through_one_redaction_door',
     '        seat = dict(_SEAT_SNAPSHOT)\n',
     '        seat = {k: (identifier(k) or "") for k in IDENTIFIERS}\n'),
    ('R7-H2b',
     'host labels are recognised by LAYOUT only again: the learned-label substitution goes, so a label in free text -- `included: <file> for <host>` -- travels intact',
     'test_every_line_this_train_prints_goes_through_one_redaction_door',
     '        for label in sorted(_LEARNED_HOSTS, key=len, reverse=True):\n            if label in out:\n                out = re.sub(r"(?<![%s])%s(?![%s])"\n                             % (_LABEL_BOUND, re.escape(label), _LABEL_BOUND),\n                             HOST_TOKEN, out)\n',
     '        pass\n'),
    ('R7-H2c',
     'the free-text line stops being a place a label can be LEARNED from, so the label is never in the set the substitution above walks',
     'test_every_line_this_train_prints_goes_through_one_redaction_door',
     '    for m in _LEARN_INCLUDED.finditer(body):\n        found.update(p.strip() for p in m.group(1).split(","))\n',
     '    pass\n'),
    ('R7-H3a',
     'the subprocess layer lets a timeout out as itself again, carrying `.cmd` -- the composed ssh destination and the --limit -- to the interpreter',
     'test_no_exception_leaves_this_train_except_through_the_door',
     '    except subprocess.TimeoutExpired:\n',
     '    except subprocess.CalledProcessError:\n'),
    ('R7-H3b',
     'the entry point catches `Fail` and nothing else, so any other exception leaves through the interpreter with a traceback whose every frame is a local path',
     'test_no_exception_leaves_this_train_except_through_the_door',
     '    except BaseException as e:                                  # noqa: BLE001\n',
     '    except ZeroDivisionError as e:                              # noqa: BLE001\n'),
    ('R7-H3c',
     "the last-resort hook prints the exception's own message instead of a redacted one",
     'test_no_exception_leaves_this_train_except_through_the_door',
     '          % (exc_type.__name__ if exc_type else "error", redact(str(exc))),\n',
     '          % (exc_type.__name__ if exc_type else "error", str(exc)),\n'),
    ('R7-M1a',
     "the recorded identity goes back to the inventory LABEL: the box's own statement is not written down, so a selector repointed at another installation satisfies the listing gate and the rollback prerequisite [re-anchored at the round-9 line]",
     'test_the_recorded_snapshot_binds_the_machine_it_was_taken_for',
     '                      "seat": dict(seat_binding_digests(seat),\n                                   box={"addr": box[0], "id": box[1]},\n                                   responder_label=_digest(responder or "")),\n',
     '                      "seat": dict(seat_binding_digests(seat),\n                                   responder_label=_digest(responder or "")),\n'),
    ('R7-M1b',
     "the listing's machine is not asked who it is: the pair recorded by phase 0 is compared with nothing",
     'test_the_recorded_snapshot_binds_the_machine_it_was_taken_for',
     '    problem = identity_problem(got, (want["addr"], want["id"]), "the listing\'s machine")\n',
     '    problem = None\n'),
    ('R7-M1c',
     'the identity is the ENDPOINT alone, so the same address reached after a rebuild -- a different installation -- reads as the same machine',
     'test_the_recorded_snapshot_binds_the_machine_it_was_taken_for',
     '    if got[1] != want[1]:\n',
     '    if False:\n'),
    ('R7-M2a',
     "a deploy play's own statement of which box it ran on is not compared with the pair that selector was attested to, so an inventory swapped between the attestation and the plays inverts the deploy order undetected [re-anchored at the round-9 line]",
     'test_each_per_box_selector_is_attested_to_its_box_before_anything_is_mutated',
     '        problem = identity_problem(identity, attested.get(key), IDENTIFIERS[key])\n',
     '        problem = None\n'),
    ('R7-M2b',
     "the deploy play is no longer asked to bring the box's identity back in its own invocation, so attestation and deployment are two resolutions of the inventory again [re-anchored at the round-9 line]",
     'test_each_per_box_selector_is_attested_to_its_box_before_anything_is_mutated',
     '        problem = identity_problem(identity, attested.get(key), IDENTIFIERS[key])\n',
     '        problem = identity_problem(attested.get(key), attested.get(key),\n                                   IDENTIFIERS[key])\n'),
    ('R7-L2a',
     'the push gate reads the configuration keys only, so a push-time rewriting (`url.<base>.pushInsteadOf`) sends the push somewhere every literal denies',
     'test_the_push_url_gate_asks_git_where_a_push_would_really_go',
     '        effective = [l.strip() for l in\n                     git_auth(["remote", "get-url", "--push", "--all", "origin"],\n                              quiet=True, merge_stderr=False).splitlines() if l.strip()]\n',
     '        effective = [want]\n'),
    ('R7-L2b',
     'an enumeration that FAILED is read as an empty set of destinations, and an unknown destination is not an empty one',
     'test_the_push_url_gate_asks_git_where_a_push_would_really_go',
     '        raise Fail("asking git for every effective push URL of `origin` did not succeed, so "\n                   "where a push would actually land is unknown -- and an unknown destination "\n                   "is not an empty one. Nothing has been pushed or deployed:\\n%s" % e)\n',
     '        effective = [want]\n'),
    ('R7-L3a',
     'the state the attestation leaves behind is not asked before the merge, the commit and the push, so a resumed run (`--from code`) reaches them with the question unasked',
     'test_each_per_box_selector_is_attested_to_its_box_before_anything_is_mutated',
     '    if len(_ATTESTED) != len(DEPLOY_LIMIT_KEYS):\n',
     '    if False:\n'),
    ('R7-L3b',
     'the code phase stops attesting for itself, so the only run that ever asks is one whose phase 0 did not skip',
     'test_each_per_box_selector_is_attested_to_its_box_before_anything_is_mutated',
     '        attest_deploy_selectors(seat_values())\n',
     '        pass\n'),
    ('R7-L4a',
     'the mergeability check writes its synthesized objects into THIS repository again, so a read-only action leaves objects behind',
     'test_the_mergeability_check_writes_its_objects_where_they_are_deleted',
     '                       env={"GIT_OBJECT_DIRECTORY": scratch,\n                            "GIT_ALTERNATE_OBJECT_DIRECTORIES": objects})\n',
     '                       )\n'),
    ('R7-L4b',
     "the module's own description of that path goes back to a claim the code does not make (R3-L3 re-executed against the round-8 wording) [re-anchored at the round-11 wrapping]",
     'test_the_mergeability_check_writes_its_objects_where_they_are_deleted',
     'The repository therefore receives no objects at\nall -- not even unreferenced ones waiting for `git gc` -- and the ordinary shape\n',
     'The repository is therefore where they land, and `git gc` clears them\neventually -- and the ordinary shape\n'),
    ('R4-L3a',
     "the box's own statement of which COMMIT its deployed clone is on is not compared with the id this train deployed (residual since round 4, closed this round)",
     'test_each_per_box_selector_is_attested_to_its_box_before_anything_is_mutated',
     '        got = box_sha(play_facts, IDENTIFIERS[key])\n        if got != sha:\n',
     '        got = sha\n        if got != sha:\n'),
    ('R4-L3b',
     'phase 7 records the rollout as verified without asking either box which commit it is on',
     'test_verify_recomputes_the_bot_policy_from_the_selected_batch',
     '        assert_boxes_are_on(code)\n',
     '        pass\n'),
    ('R8-X1',
     "the capture writes WHATEVER address answered: the listing is asked of the virtualisation host, whose address this train does not declare, so a fourth machine's address is copied into the evidence file (found by running the capture this round) [re-anchored at the round-9 line]",
     'test_the_captured_listing_is_built_from_records_and_everything_else_is_dropped',
     '                % (endpoint_class(who[0]) if who else NONE_TOKEN,\n',
     '                % (who[0] if who else NONE_TOKEN,\n'),
    ('R6-H2a',
     "the door is opened: the module stops shadowing `print`, so every one of the train's own lines reaches stdout exactly as it was composed (re-executed)",
     'test_every_line_this_train_prints_goes_through_one_redaction_door',
     '    _emit(*[redact(a) if isinstance(a, str) else a for a in args], **kwargs)\n',
     '    _emit(*args, **kwargs)\n'),
    ('R6-H2b',
     'the door substitutes seat VALUES only, so every host label ansible writes beside them travels intact -- BOTH mechanisms removed, because the layout rules are redundant once a label is learned and taken out wherever it stands (re-executed, re-scoped)',
     'test_every_line_this_train_prints_goes_through_one_redaction_door',
     '        out = _LABEL_IN_BRACKETS.sub(r"\\g<1>%s\\g<2>" % HOST_TOKEN, out)\n        out = _RECAP_ROW.sub(r"\\g<1>%s\\g<2>" % HOST_TOKEN, out)\n        out = _ADHOC_ROW.sub(r"\\g<1>%s\\g<2>" % HOST_TOKEN, out)\n        for label in sorted(_LEARNED_HOSTS, key=len, reverse=True):\n            if label in out:\n                out = re.sub(r"(?<![%s])%s(?![%s])"\n                             % (_LABEL_BOUND, re.escape(label), _LABEL_BOUND),\n                             HOST_TOKEN, out)\n',
     '        pass\n'),
    ('R6-M1a',
     'phase 0 records the selectors it asked for and nothing about the machine that answered, so a selector remapped to another box satisfies every later gate (re-executed) [re-anchored at the round-9 line]',
     'test_the_recorded_snapshot_binds_the_machine_it_was_taken_for',
     '                      "seat": dict(seat_binding_digests(seat),\n                                   box={"addr": box[0], "id": box[1]},\n                                   responder_label=_digest(responder or "")),\n',
     '                      "seat": seat_binding_digests(seat),\n'),
    ('R6-M1b',
     'the listing gate stops asking whether the machine that answered is the machine the snapshot play ran against (re-executed)',
     'test_the_recorded_snapshot_binds_the_machine_it_was_taken_for',
     '    responder = responder_problem(st.get("snapshot"), listing)\n    if responder:\n',
     '    responder = None\n    if responder:\n'),
    ('R6-M1c',
     'phase 0 re-reads the seat between using a value and digesting it (re-executed)',
     'test_the_recorded_snapshot_binds_the_machine_it_was_taken_for',
     '    target = snapshot_target(seat)\n',
     '    target = snapshot_target()\n'),
    ('R6-M2a',
     'minting provenance goes: a name the container was ALREADY holding is accepted as the rollback point this train took (re-executed)',
     'test_a_snapshot_name_is_the_exact_form_the_wrapper_mints',
     '    if name in before_names:\n',
     '    if False:\n'),
    ('R6-M2b',
     'freshness is judged from the moment of RECORDING again (re-executed)',
     'test_the_recorded_snapshot_binds_to_this_train_its_label_its_age_and_the_listing',
     '        taken = datetime.fromisoformat(minted["before_utc"])\n',
     '        taken = datetime.fromisoformat(rec["created_utc"])\n'),
    ('R6-M2c',
     'the stamp grammar goes back to `\\d`, which is Unicode-wide in Python (re-executed)',
     'test_a_snapshot_name_is_the_exact_form_the_wrapper_mints',
     '_CC_STAMP = r"[0-9]{8}_[0-9]{6}"\n',
     '_CC_STAMP = r"\\d{8}_\\d{6}"\n'),
    ('R6-M3a',
     'the deploy step stops attesting its two selectors (re-executed) [re-anchored at the round-10 line]',
     'test_each_per_box_selector_is_attested_to_its_box_before_anything_is_mutated',
     '        problem = identity_problem((token, fingerprint), attested.get(key), IDENTIFIERS[key])\n',
     '        problem = None\n'),
    ('R6-M3b',
     'the attestation runs and compares nothing: the selector resolves to one machine and no one asks whether it is the right one (re-executed) [re-anchored at the round-9 line]',
     'test_each_per_box_selector_is_attested_to_its_box_before_anything_is_mutated',
     '    if want_token and token != want_token:\n',
     '    if False and token != want_token:\n'),
    ('R6-M3c',
     'phase 0 takes the rollback point without attesting anything first (re-executed)',
     'test_each_per_box_selector_is_attested_to_its_box_before_anything_is_mutated',
     '    if args.go:\n        attest_deploy_selectors(seat)\n',
     '    if False:\n        attest_deploy_selectors(seat)\n'),
    ('R6-L1',
     'the zone alternative loses its end-of-token boundary (re-executed)',
     'test_a_zone_less_listing_time_is_unknown_and_never_read_as_UTC',
     '(Z|UTC|GMT|[+-][0-9]{2}:?[0-9]{2})(?=\\s|\\Z))?")',
     '(Z|UTC|GMT|[+-][0-9]{2}:?[0-9]{2}))?")'),
    ('R6-L3',
     'only the LAST configured push URL is read (`--get` in place of `--get-all`) (re-executed)',
     'test_the_merge_is_authenticated_and_the_remote_checked_before_the_push',
     '        out = git_auth(["config", "--get-all", name], quiet=True, merge_stderr=False)\n',
     '        out = git_auth(["config", "--get", name], quiet=True, merge_stderr=False)\n'),
    ('R5-H1a',
     "the deploy play's per-box selector stops being a seat value and goes back to a literal in the train (re-executed)",
     'test_the_two_per_box_deploy_limits_are_seat_values_checked_by_one_grammar',
     '        limit = checked_target(key, seat)\n',
     '        limit = "a-fixed-group"\n'),
    ('R5-H2a',
     'the binding predicate goes back to testing a PREFIX (re-executed)',
     'test_a_snapshot_name_is_the_exact_form_the_wrapper_mints',
     '    return bool(name) and bool(cc_name_re().match(name))\n',
     '    return bool(name) and bool(re.match(r"^cc_%s_" % re.escape(SNAPSHOT_LABEL or ""),\n                                        name))\n'),
    ('R5-H2b',
     'the name grammar goes back to a SHAPE -- cc_ plus anything (re-executed)',
     'test_a_snapshot_name_is_the_exact_form_the_wrapper_mints',
     '    src = cc_name_pattern()\n    return re.compile(r"^%s\\Z" % src) if src else re.compile(r"(?!)")\n',
     '    return re.compile(r"^cc_[A-Za-z0-9_.:-]+\\Z")\n'),
    ('R5-M1a',
     'the rollback prerequisite stops asking WHICH MACHINE the snapshot was taken for (re-executed)',
     'test_the_recorded_snapshot_binds_the_machine_it_was_taken_for',
     '    seat = seat_binding_problem(rec, "the rollback prerequisite")\n    if seat:\n        return seat\n',
     '    seat = None\n    if seat:\n        return seat\n'),
    ('R5-M1c',
     'a record written before the seat binding existed is treated as bound (re-executed)',
     'test_the_recorded_snapshot_binds_the_machine_it_was_taken_for',
     '    bound = rec.get("seat")\n    if not isinstance(bound, dict) or not bound:\n',
     '    bound = rec.get("seat") or {}\n    if False:\n'),
    ('R5-L3a',
     'the push goes back to running before the remote is validated (re-executed)',
     'test_the_merge_is_authenticated_and_the_remote_checked_before_the_push',
     '        assert_origin_is_the_expected_remote()\n        git(["push", "origin", "main"])\n',
     '        git(["push", "origin", "main"])\n        assert_origin_is_the_expected_remote()\n'),
    ('R5-L4',
     "ansible's reserved patterns are accepted as targets again (re-executed)",
     'test_the_snapshot_play_and_the_snapshot_listing_are_aimed_at_one_target',
     '    if value.lower() in _TARGET_RESERVED:\n',
     '    if False:\n'),
    ('R5-L5',
     'the object-id grammar goes back to `$` (re-executed)',
     'test_the_two_provenance_anchors_are_object_ids_and_the_transcript_prints_them_whole',
     '_FULL_SHA = re.compile(r"^[0-9a-f]{40}\\Z")\n',
     '_FULL_SHA = re.compile(r"^[0-9a-f]{40}$")\n'),
    ('R4-H1',
     "the batch's two provenance anchors are no longer shape-checked at selection (re-executed)",
     'test_the_two_provenance_anchors_are_object_ids_and_the_transcript_prints_them_whole',
     '        if value is None:\n            continue\n        if not isinstance(value, str) or not _FULL_SHA.match(value):',
     '        if value is None or True:\n            continue\n        if not isinstance(value, str) or not _FULL_SHA.match(value):'),
    ('R4-H3',
     "the capture keeps the wrapper's own lines instead of dropping what it cannot name (re-executed)",
     'test_the_captured_listing_is_built_from_records_and_everything_else_is_dropped',
     '        dropped += 1\n    return records, dropped',
     '        records.append(line)\n    return records, dropped'),
    ('R4-M1',
     'the listing reads its own configured key again instead of the one value the snapshot play is also aimed at (re-executed) [re-anchored at the round-9 line]',
     'test_the_snapshot_play_and_the_snapshot_listing_are_aimed_at_one_target',
     '    target = snapshot_target(values)\n    play_out, sections, identity, responder = run_attested(\n',
     '    target = require_identifier("pve_group")\n    play_out, sections, identity, responder = run_attested(\n'),
    ('R4-L2',
     'a machine that did not answer leaves no block again (re-executed) [re-anchored at the round-9 line]',
     'test_a_machine_that_did_not_answer_the_listing_is_still_one_of_the_machines',
     '    if unreachable != "0" or failed != "0":\n',
     '    if False:\n'),
    ('R4-L4',
     'the one git door stops setting GIT_NO_REPLACE_OBJECTS (re-executed)',
     'test_every_git_subprocess_the_train_spawns_disables_object_replacement',
     '    env = dict(GIT_NO_REPLACE, **(kw.pop("env", None) or {}))\n',
     '    env = dict(kw.pop("env", None) or {}) or None\n'),
    ('R3-H1',
     "the recorded code SHA's shape is not asked of the raw state string (re-executed)",
     'test_the_recorded_code_sha_is_an_object_id_and_that_id_is_what_deploys',
     '    shape = code_sha_shape_problem(st)\n    if shape:',
     '    shape = None\n    if shape:'),
    ('R3-H2',
     'authenticating git commands stop carrying --no-replace-objects (re-executed)',
     'test_authenticating_git_runs_without_replacements_and_the_remote_must_hold_the_merge',
     '    return git(["--no-replace-objects"] + list(args), **kw)',
     '    return git(list(args), **kw)'),
    ('R3-M2',
     'phase 0 skips on the metadata alone again (re-executed)',
     'test_phase_zero_takes_a_fresh_snapshot_when_the_recorded_one_is_no_longer_listed',
     '    problem, how = snapshot_binding(st)',
     '    problem, how = snapshot_record_problem(st), None'),
    ('R2-H1a',
     'the universal clean gate is not asked (re-executed)',
     'test_the_code_phase_refuses_a_dirty_tree_and_a_merge_that_is_not_the_reviewed_content',
     '    assert_clean_tree("this phase is about to check out main and merge %s onto it" % BRANCH)',
     '    pass'),
    ('R2-H1b',
     "the merge's tree is not compared (re-executed)",
     'test_the_code_phase_refuses_a_dirty_tree_and_a_merge_that_is_not_the_reviewed_content',
     '    got_tree = _tree_of(sha)',
     '    got_tree = want_tree'),
    ('R2-M1',
     'the snapshot prerequisite is truthiness again (re-executed)',
     'test_the_recorded_snapshot_binds_to_this_train_its_label_its_age_and_the_listing',
     '    problem = snapshot_record_problem(st)\n    if args.go and problem:',
     '    problem = None if st.get("snapshot") else "no snapshot"\n    if args.go and problem:'),
    ('R2-M2',
     'the post-merge arm is removed (re-executed)',
     'test_the_code_phase_accepts_main_at_its_own_merge_and_refuses_it_anywhere_else',
     '    if authenticated:\n        want_now = authenticated',
     '    if False:\n        want_now = authenticated'),
    ('R2-L1',
     '--batch picks a batch for the operator again instead of refusing (re-executed)',
     'test_the_train_refuses_to_run_when_no_batch_is_named',
     '    ap.add_argument("--batch", choices=sorted(BATCHES), default=None,',
     '    ap.add_argument("--batch", choices=sorted(BATCHES), default=sorted(BATCHES)[0],'),
    ('R8-A1a',
     "the renderer stops asking its own schema, so a document the schema forbids is emitted and the pin's only remaining check is the one in the pin",
     'test_the_review_summary_is_a_schema_document_and_carries_no_free_text',
     '        problem = summary_problem(doc)\n',
     '        problem = None\n'),
    ('R8-A1b',
     'no value is refused for its type, so a play tail, an exception message or a box-reported label travels inside a field that has no text type',
     'test_the_review_summary_is_a_schema_document_and_carries_no_free_text',
     '    return "not a value of its type (%s)" % " or ".join(_TYPE_WORDS[k] for k in types)\n',
     '    return None\n'),
    ('R8-A1c',
     'a key the schema does not define is admitted, so a field nothing declared rides into the document beside the declared ones',
     'test_the_review_summary_is_a_schema_document_and_carries_no_free_text',
     '        if key not in singles and key not in rows:\n',
     '        if False:\n'),
    ('R9-A1d',
     'a document that lost a key is not refused for it, so a truncated render or a hand edit reads as complete',
     'test_the_review_summary_is_a_schema_document_and_carries_no_free_text',
     '        if key not in doc:\n            return "the %s document is missing the key %r" % (artifact, key)\n',
     '        if False:\n            return "the %s document is missing the key %r" % (artifact, key)\n'),
    ('R9-A1e',
     'a word is judged by its SHAPE again, so an upper-cased machine or group name is admitted as a vocabulary word',
     'test_the_review_summary_is_a_schema_document_and_carries_no_free_text',
     '    if kind == T_WORD:\n        return value in summary_words()\n',
     '    if kind == T_WORD:\n        return bool(re.match(r"\\A[A-Z][A-Z0-9_]*\\Z", value))\n'),
    ('R9-A1f',
     'a single key is checked against EVERY type rather than its own, so a number where a word is typed, or a word where a number is, passes',
     'test_the_review_summary_is_a_schema_document_and_carries_no_free_text',
     '        bad = summary_scalar_problem(doc[key], singles[key])\n',
     '        bad = summary_scalar_problem(doc[key])\n'),
    ('R9-A1g',
     'a key the run never reached is left out instead of reading UNRECORDED, so every render of a partial run is refused as incomplete',
     'test_the_review_summary_is_a_schema_document_and_carries_no_free_text',
     '        for key in SUMMARY_SINGLES[artifact]:\n            doc.setdefault(key, UNRECORDED)\n',
     '        for key in SUMMARY_SINGLES[artifact]:\n            pass\n'),
    ('R9-A1h',
     'a key a row section does not define is admitted inside a row',
     'test_the_review_summary_is_a_schema_document_and_carries_no_free_text',
     '                if rkey not in spec:\n',
     '                if False:\n'),
    ('R8-A2',
     'the documents are printed OUTSIDE the two fences, so what a reader parses between them is not what the train rendered',
     'test_the_summary_is_emitted_between_two_fences_and_nothing_else_writes',
     '    print(SUMMARY_OPEN)\n    print(json.dumps(summary_documents(), indent=1, sort_keys=True))\n    print(SUMMARY_CLOSE)\n',
     '    print(json.dumps(summary_documents(), indent=1, sort_keys=True))\n    print(SUMMARY_OPEN)\n    print(SUMMARY_CLOSE)\n'),
    ('R8-H2a',
     "the seat may be read again after capture, so a value edited between two reads puts today's text into a command composed from yesterday's",
     'test_the_seat_is_captured_on_first_read_and_cannot_be_read_again',
     '    if key in _SEAT_SNAPSHOT:\n        raise Fail("the seat has already been read for %r in this process, and it is read "\n',
     '    if False:\n        raise Fail("the seat has already been read for %r in this process, and it is read "\n'),
    ('R8-H2b',
     'the capture answers the ARGUMENT rather than the captured value, so a second path through it travels with a value the door does not know',
     'test_the_seat_is_captured_on_first_read_and_cannot_be_read_again',
     '    _SEAT_SNAPSHOT.setdefault(key, value)\n    return _SEAT_SNAPSHOT[key]\n',
     '    _SEAT_SNAPSHOT.setdefault(key, value)\n    return value\n'),
    ('R8-H2c',
     'the label shape needs two characters again, so a one-character host label is never learned and never substituted',
     'test_the_seat_is_captured_on_first_read_and_cannot_be_read_again',
     '_LABEL_SHAPE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*\\Z")\n',
     '_LABEL_SHAPE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*[A-Za-z0-9]\\Z")\n'),
    ('R8-H3a',
     "no hook is installed before the imports that can fail, so an import error is a traceback whose every frame is this file's absolute path",
     'test_the_door_exists_before_anything_that_can_fail_and_has_no_path_around_it',
     'sys.excepthook = _bootstrap_excepthook\n',
     'sys.excepthook = sys.__excepthook__\n'),
    ('R8-H3b',
     'argparse writes its diagnostics straight to the file object again, so the argument the operator mistyped -- often a path -- goes out around the door',
     'test_the_door_exists_before_anything_that_can_fail_and_has_no_path_around_it',
     '    def _print_message(self, message, file=None):\n        if message:\n            print(message.rstrip("\\n"))\n',
     '    def _print_message(self, message, file=None):\n        if message:\n            _emit(message.rstrip("\\n"))\n'),
    ('R8-H3c',
     'a failure inside the door returns the partially substituted line again, so a failure in the first rule returns the input unchanged',
     'test_the_door_exists_before_anything_that_can_fail_and_has_no_path_around_it',
     '        return UNREDACTABLE_LINE\n',
     '        return out\n'),
    ('R8-H3d',
     'a SystemExit carrying a string is re-raised, and the interpreter prints that string verbatim -- which is the argument argparse did not understand',
     'test_the_door_exists_before_anything_that_can_fail_and_has_no_path_around_it',
     '        if isinstance(e.code, str):\n',
     '        if False:\n'),
    ('R8-H4a',
     'the recorded fingerprint is summarised as ITSELF instead of as RECORDED, so a persistent machine identifier is in every transcript that prints the state',
     'test_the_review_summary_is_a_schema_document_and_carries_no_free_text',
     '        "snapshot_fingerprint": "RECORDED" if box.get("id") else "MISSING",\n',
     '        "snapshot_fingerprint": box.get("id") or "MISSING",\n'),
    ('R8-H4b',
     'one reading reads as agreement again, so a phase that managed a single probe reports MATCH for a comparison that never happened',
     'test_the_review_summary_is_a_schema_document_and_carries_no_free_text',
     '    if len(got) != len(list(readings)) or len(got) < 2:\n',
     '    if len(got) != len(list(readings)) or len(got) < 1:\n'),
    ('R8-H4c',
     'the door stops tokenising 64-hex runs, so a fingerprint inside output this train did not compose reaches the terminal as itself',
     'test_every_line_this_train_prints_goes_through_one_redaction_door',
     '        out = _ANY_FINGERPRINT.sub(FINGERPRINT_TOKEN, out)\n',
     '        pass\n'),
    ('R8-H5a',
     'the address a box reported is returned verbatim instead of as its class, so an endpoint this train does not declare is written into the state file',
     'test_one_ansible_process_carries_the_facts_and_the_play_they_attest',
     '    token = endpoint_token(addrs[0])\n',
     '    token = addrs[0]\n'),
    ('R8-M1a',
     'the composed playbook loses its closing facts play, so the box states who it is before the work and nothing after it',
     'test_one_ansible_process_carries_the_facts_and_the_play_they_attest',
     '    plays.append(_facts_play(AFTER, listing=listing))\n',
     '    plays.append(_facts_play(AFTER, listing=listing)) if False else None\n'),
    ('R8-M1b',
     'a section marker carrying a token this invocation did not mint is accepted, so a block another process printed supplies the facts',
     'test_one_ansible_process_carries_the_facts_and_the_play_they_attest',
     '    strangers = [m for m in marks if m.group(4) != nonce]\n',
     '    strangers = []\n'),
    ('R8-M1c',
     'the order of the sections is not required, so facts that came back after the play are read as the facts taken before it',
     'test_one_ansible_process_carries_the_facts_and_the_play_they_attest',
     '    if order != list(want):\n',
     '    if False:\n'),
    ('R8-M1d',
     "a duplicated section is accepted, so two machines' accounts inside one marked pair read as one machine's",
     'test_one_ansible_process_carries_the_facts_and_the_play_they_attest',
     '            if key in open_at or key in bodies:\n',
     '            if False:\n'),
    ('R8-M1e',
     'a refused attestation leaves the status the operation could have set standing, so a play that reported failed=0 is recorded as a success nothing attested',
     'test_one_ansible_process_carries_the_facts_and_the_play_they_attest',
     '        for key in status_keys or ():\n            st[key] = "REFUSED"\n',
     '        for key in status_keys or ():\n            pass\n'),
    ('R8-M2a',
     'the attested run stops importing the play it attests, so the facts and the work are two processes and two inventory resolutions again [re-anchored at the round-10 line]',
     'test_one_ansible_process_carries_the_facts_and_the_play_they_attest',
     '    book = attested_playbook(play_path=play_path, listing=listing, gate=expect is not None)\n',
     '    book = attested_playbook(play_path=None, listing=listing, gate=expect is not None)\n'),
    ('R8-M2b',
     "the facts task echoes a constant instead of the invocation's own variable, so the marker no longer proves which process rendered it",
     'test_one_ansible_process_carries_the_facts_and_the_play_they_attest',
     '    return (\'echo "%s-BEGIN %s {{ scr_nonce }}"; \'\n            \'echo "%s {{ ansible_host | default(inventory_hostname) }}"; \'\n',
     '    return (\'echo "%s-BEGIN %s 00000000000000000000000000000000"; \'\n            \'echo "%s {{ ansible_host | default(inventory_hostname) }}"; \'\n'),
    ('R9-D1',
     "the post-code phase's gate is a truth test again, so the word REFUSED that a refused attestation writes reads as the code being live and the phase runs [re-anchored at the round-10 line]",
     'test_one_ansible_process_carries_the_facts_and_the_play_they_attest',
     '    if args.go and st.get("code_deployed") is not True:\n        raise Fail("code SHA is not live',
     '    if args.go and not st.get("code_deployed"):\n        raise Fail("code SHA is not live'),
    ('R9-D2',
     'the summary reads a refused deploy by its truth value again, so REFUSED is reported as YES [re-anchored at the round-10 line]',
     'test_one_ansible_process_carries_the_facts_and_the_play_they_attest',
     '        "code_deployed": _status_word(st.get("code_deployed")),\n',
     '        "code_deployed": ("YES" if st.get("code_deployed") else "NO"),\n'),
    ('R9-D3',
     'the summary reads a refused snapshot as a record again, so the word REFUSED is dereferenced as a dict and the check crashes instead of reporting it',
     'test_one_ansible_process_carries_the_facts_and_the_play_they_attest',
     '    snap = raw_snap if isinstance(raw_snap, dict) else {}\n',
     '    snap = raw_snap or {}\n'),
    ('R9-B10a',
     'a missing key reads as the OLD build and a present one as the NEW build',
     'test_an_ABSENT_json_marker_reads_a_missing_key_as_the_NEW_build',
     '            (matched if got is _MISSING else missing).append(m["key"])\n',
     '            (missing if got is _MISSING else matched).append(m["key"])\n'),
    ('R9-B10b',
     'the control field is no longer required to hold, so a body with the control false or gone is read as a verdict about the build',
     'test_an_ABSENT_json_marker_reads_a_missing_key_as_the_NEW_build',
     '            if not reading_matches(ctl, m["control_expect"]):\n                continue          # the control failed: this reading is not a verdict\n',
     '            if False:\n                continue          # the control failed: this reading is not a verdict\n'),
    ('R9-B10c',
     'an ABSENT marker that names no control, or gives it no value, is accepted',
     'test_the_train_refuses_an_ABSENT_marker_that_carries_no_control',
     '                    if m.get(field) is None:\n',
     '                    if False:\n'),
    ('R9-B10d',
     'an ABSENT marker may name itself as its own control',
     'test_the_train_refuses_an_ABSENT_marker_that_carries_no_control',
     '                if m["control_key"] == m["key"]:\n',
     '                if False:\n'),
    ('R9-B10e',
     'a control whose expected value is the ABSENT sentinel is accepted',
     'test_the_train_refuses_an_ABSENT_marker_that_carries_no_control',
     '                if m["control_expect"] is ABSENT:\n',
     '                if False:\n'),
    ('R9-B10f',
     'a marker expecting None is accepted again',
     'test_the_train_refuses_an_ABSENT_marker_that_carries_no_control',
     '            if m.get("expect") is None:\n',
     '            if False:\n'),
    ('R9-B10g',
     'the sentinel compares equal to its own spelling, so a body carrying the string ABSENT satisfies it',
     'test_the_ABSENT_sentinel_is_value_unequal_to_its_own_spelling',
     '        return self is other\n',
     '        return self is other or other == "ABSENT"\n'),
    ('R9-D4',
     'the play after the operation states its facts before it reads the listing again, so the composed playbook emits an order the answer parser refuses',
     'test_one_ansible_process_carries_the_facts_and_the_play_they_attest',
     '    if phase == AFTER:\n        steps = steps[::-1]\n',
     '    if phase == AFTER:\n        steps = steps\n'),
    ('R9-D5',
     'the composition is no longer checked before anything is spawned, so a playbook that emits another order is sent to the controller',
     'test_one_ansible_process_carries_the_facts_and_the_play_they_attest',
     '    if composed_order(book) != opening + ([None] if play_path else []) + closing:\n',
     '    if False:\n'),
    ('R9-D6',
     'the composed order no longer marks where the imported play runs, so the check cannot say that the facts bracket it',
     'test_one_ansible_process_carries_the_facts_and_the_play_they_attest',
     '            order.append(None)\n            continue\n',
     '            continue\n'),
    ('R8-L4a',
     'a resumed code SHA is trusted for its SHAPE again, so `--only verify` checks the boxes against a 40-character string nothing authenticated',
     'test_a_dry_run_records_no_state_and_a_resumed_sha_is_authenticated',
     '        code = authenticated_code_sha(code, "persisted")\n',
     '        code = code\n'),
    ('R8-L4b',
     'the reviewed tip need not be inside the recorded commit, so the boxes are checked against a commit the reviewed code is not in',
     'test_a_dry_run_records_no_state_and_a_resumed_sha_is_authenticated',
     '        if REVIEWED_TIP and not _git_auth_succeeds(\n',
     '        if False and not _git_auth_succeeds(\n'),
    ('R8-L5',
     'a dry run records `verified` and writes the state file again, about a rollout it deliberately did not ask the exact-SHA question of',
     'test_a_dry_run_records_no_state_and_a_resumed_sha_is_authenticated',
     '    if not args.go:\n        print("  [dry run] nothing is recorded: `verified` is not set and the state file is "\n',
     '    if False:\n        print("  [dry run] nothing is recorded: `verified` is not set and the state file is "\n'),
    ('R8-L6a',
     'the binding question is not asked before the phases, so a run bound to the wrong main attests a selector and mints a snapshot before the refusal that exists to stop it',
     'test_the_binding_question_is_asked_before_phase_zero_can_mint_anything',
     '    assert_provenance_up_front(args, st)\n',
     '    _PROVENANCE.clear()\n'),
    ('R8-L6b',
     'the refusal stops a DRY run too, so the plan hides every phase below it -- including the OLD-build negative control phase 4 carries',
     'test_the_binding_question_is_asked_before_phase_zero_can_mint_anything',
     '        if not args.go:\n            print("\\n  [plan only] a run would REFUSE HERE, before phase 0 attests a selector, "\n',
     '        if True:\n            raise\n        if not args.go:\n            print("\\n  [plan only] a run would REFUSE HERE, before phase 0 attests a selector, "\n'),
    ('R8-M1f',
     "the recap's counters are not read, so a group whose intended machine was unreachable and whose second member answered reads as one healthy responder",
     'test_a_machine_that_did_not_answer_the_listing_is_still_one_of_the_machines',
     '    if unreachable != "0" or failed != "0":\n',
     '    if False:\n'),
    ('R10-M1a',
     'run_attested stops reading the process exit status, so an answer from a playbook that failed -- a listing whose wrapper exited 2 -- is parsed as an answer',
     'test_r10_m1_the_listing_status_is_the_process_status_and_no_listed_text_is_one',
     '    if rc != 0:\n        tail = ',
     '    if False:\n        tail = '),
    ('R10-M1b',
     "the listing task opts out of ansible's failure rule the way the facts task does, so a wrapper that exits non-zero no longer fails the playbook",
     'test_r10_m1_the_listing_status_is_the_process_status_and_no_listed_text_is_one',
     '        if name == "facts":\n',
     '        if True:\n'),
    ('R10-M1c',
     'the listing command exits 0 whatever the wrapper exited',
     'test_r10_m1_the_listing_status_is_the_process_status_and_no_listed_text_is_one',
     '\'echo "%s-END %s {{ scr_nonce }}"; exit $__scr_list_rc\'',
     '\'echo "%s-END %s {{ scr_nonce }}"; exit 0\''),
    ('R10-M1d',
     'the controller-side shell exits 0 whatever the playbook exited [re-anchored at the round-12 line: a command appended after the invocation]',
     'test_r10_m1_the_listing_status_is_the_process_status_and_no_listed_text_is_one',
     '--limit %s -e scr_nonce=%s%s%s"\n',
     '--limit %s -e scr_nonce=%s%s%s; exit 0"\n'),
    ('R10-M2a',
     "the deploy step re-attests the selectors itself, so a selector remapped after the phase's attestation is attested afresh and deployed to (the round-9 behaviour)",
     'test_each_per_box_selector_is_attested_to_its_box_before_anything_is_mutated',
     '    attested = dict(_ATTESTED)\n',
     '    attested = attest_deploy_selectors(seat)\n'),
    ('R10-M2b',
     'the per-box check is never asked, so the standby is deployed behind a primary nothing has seen serve the new build',
     'test_r10_m2_a_box_that_does_not_serve_the_new_build_stops_the_next_box_play',
     '        if after_box is not None:\n            after_box(host)\n',
     '        if False:\n            after_box(host)\n'),
    ('R10-M2c',
     'the code phase stops handing its deploy the per-box NEW-build check',
     'test_r10_m2_a_box_that_does_not_serve_the_new_build_stops_the_next_box_play',
     '    _deploy_both(sha, st=st, status_key="code_deployed", after_box=assert_box_runs_new)\n',
     '    _deploy_both(sha, st=st, status_key="code_deployed", after_box=None)\n'),
    ('R10-M2d',
     'the precursor phase stops handing its deploy the per-box OLD-build check',
     'test_r10_m2_a_box_that_does_not_serve_the_new_build_stops_the_next_box_play',
     '    _deploy_both(sha, st=st, status_key="precursor_deployed", after_box=assert_box_still_old)\n',
     '    _deploy_both(sha, st=st, status_key="precursor_deployed", after_box=None)\n'),
    ('R10-M2e',
     "the gate's own PASSED line is no longer required, so a gate that printed nothing passes",
     'test_r10_m2_the_identity_gate_runs_in_the_play_process_and_must_say_it_passed',
     '        if "PASSED" not in verdicts or "REFUSED" in verdicts:\n',
     '        if False:\n'),
    ('R10-M2f',
     'a gate in a play that is not any_errors_fatal counts as composed',
     'test_r10_m2_the_identity_gate_runs_in_the_play_process_and_must_say_it_passed',
     '                    and play.get("any_errors_fatal") is True):\n',
     '                    ):\n'),
    ('R10-M2g',
     'the gate is handed the fingerprint itself instead of the token-salted digest',
     'test_r10_m2_the_identity_gate_runs_in_the_play_process_and_must_say_it_passed',
     '                      % (expected_identity_digest(nonce, fingerprint), addr))\n',
     '                      % (fingerprint, addr))\n'),
    ('R10-M3a',
     "the code phase writes no attempt sentinel, so an earlier attempt's True stands over a partial deploy and --from i18n passes",
     'test_r10_m3_an_attempt_that_does_not_finish_leaves_a_word_no_gate_accepts',
     '    if args.go:\n        begin_attempt(st, "code_deployed")\n',
     '    if False:\n        begin_attempt(st, "code_deployed")\n'),
    ('R10-M3b',
     'the precursor deploy writes no attempt sentinel',
     'test_r10_m3_an_attempt_that_does_not_finish_leaves_a_word_no_gate_accepts',
     '    begin_attempt(st, "precursor_deployed")\n',
     '    pass\n'),
    ('R10-M3c',
     'the schema phase writes no attempt sentinel',
     'test_r10_m3_an_attempt_that_does_not_finish_leaves_a_word_no_gate_accepts',
     '    begin_attempt(st, "schema_done")\n',
     '    pass\n'),
    ('R10-M3d',
     'the i18n phase writes no attempt sentinel',
     'test_r10_m3_an_attempt_that_does_not_finish_leaves_a_word_no_gate_accepts',
     '    begin_attempt(st, "i18n_done")   # R9-M3: before the first migrate\n',
     '    pass\n'),
    ('R10-M3e',
     'the bot phase writes no attempt sentinel',
     'test_r10_m3_an_attempt_that_does_not_finish_leaves_a_word_no_gate_accepts',
     '    begin_attempt(st, "bot_deployed")   # R9-M3: before the deploy-bot verb\n',
     '    pass\n'),
    ('R10-M3f',
     "the verify phase writes no attempt sentinel, so a refused verify leaves an earlier verify's True standing",
     'test_r10_m3_an_attempt_that_does_not_finish_leaves_a_word_no_gate_accepts',
     '    if args.go:\n        begin_attempt(st, "verified")\n',
     '    if False:\n        begin_attempt(st, "verified")\n'),
    ('R10-M3g',
     'the sentinel is written into the in-memory state only and never persisted, so a later process reads the earlier True',
     'test_r10_m3_an_attempt_that_does_not_finish_leaves_a_word_no_gate_accepts',
     '    st[key] = ATTEMPTED\n    save_state(st)\n',
     '    st[key] = ATTEMPTED\n'),
    ('R10-M4a',
     'the seat file is re-opened for every key, so a replacement between two reads makes a hybrid seat',
     'test_r10_m4_the_seat_file_is_read_once_and_a_replacement_cannot_make_a_hybrid',
     '    if "read" not in _SEAT_FILE:\n',
     '    if True:\n'),
    ('R10-M4b',
     'the recorded digest is a second read of the file rather than the digest of the bytes the values were parsed from',
     'test_r10_m4_the_seat_file_is_read_once_and_a_replacement_cannot_make_a_hybrid',
     '    return seat_file()[1]\n',
     '    return hashlib.sha256(open(TRAIN_CONF, "rb").read()).hexdigest()\n'),
    ('R10-M5a',
     "the schema phase's precursor gate is a truth test, so REFUSED reads as a precursor deploy that passed",
     'test_r10_m5_every_gate_accepts_only_the_exact_success_word',
     '    if st.get("precursor_deployed") is not True:\n',
     '    if not st.get("precursor_deployed"):\n'),
    ('R10-M5b',
     "the code phase's schema gate is a truth test",
     'test_r10_m5_every_gate_accepts_only_the_exact_success_word',
     '    if args.go and ALL_SQL and st.get("schema_done") is not True:\n',
     '    if args.go and ALL_SQL and not st.get("schema_done"):\n'),
    ('R10-M5c',
     'the relocated old-build control is skipped on any truthy word, not only on the exact True',
     'test_r10_m5_every_gate_accepts_only_the_exact_success_word',
     '    if not ALL_SQL and st.get("pre_code_old_build") is not True:\n',
     '    if not ALL_SQL and not st.get("pre_code_old_build"):\n'),
    ('R10-M5d',
     "the i18n phase's code gate is a truth test",
     'test_r10_m5_every_gate_accepts_only_the_exact_success_word',
     '    if args.go and st.get("code_deployed") is not True:\n        raise Fail("code SHA is not live',
     '    if args.go and not st.get("code_deployed"):\n        raise Fail("code SHA is not live'),
    ('R10-M5e',
     "the bot phase's i18n gate is a truth test",
     'test_r10_m5_every_gate_accepts_only_the_exact_success_word',
     '    if args.go and st.get("i18n_done") is not True:\n',
     '    if args.go and not st.get("i18n_done"):\n'),
    ('R10-M5f',
     "the bot phase's code gate is a truth test",
     'test_r10_m5_every_gate_accepts_only_the_exact_success_word',
     '    if args.go and st.get("code_deployed") is not True:\n        raise Fail("the code phase has not passed',
     '    if args.go and not st.get("code_deployed"):\n        raise Fail("the code phase has not passed'),
    ('R10-M5g',
     "verify's bot gate is a truth test",
     'test_r10_m5_every_gate_accepts_only_the_exact_success_word',
     '        if args.go and st.get("bot_deployed") is not True:\n',
     '        if args.go and not st.get("bot_deployed"):\n'),
    ('R10-M5h',
     'the one reading every summary status goes through says YES for any truthy word',
     'test_r10_m5_every_gate_accepts_only_the_exact_success_word',
     '    if value is True:\n        return "YES"\n',
     '    if value:\n        return "YES"\n'),
    ('R10-L5a',
     'repair-state records a repair and removes nothing',
     'test_r10_l5_repair_state_clears_an_unbacked_verified_and_a_dry_run_cannot_write_one',
     '        del st[r["key"]]\n',
     '        pass\n'),
    ('R10-L5b',
     'repair-state writes the state file without --go',
     'test_r10_l5_repair_state_clears_an_unbacked_verified_and_a_dry_run_cannot_write_one',
     '    if not go:\n        for r in repairs:\n',
     '    if False:\n        for r in repairs:\n'),
    ('R10-L5c',
     'a bare verified True counts as backed, so repair-state finds nothing to clear',
     'test_r10_l5_repair_state_clears_an_unbacked_verified_and_a_dry_run_cannot_write_one',
     '    return (st.get("verified") is True and isinstance(ev, dict) and ev.get("mode") == "GO"\n',
     '    return (st.get("verified") is True or isinstance(ev, dict) and ev.get("mode") == "GO"\n'),
    ('R10-L5d',
     'a GO verify writes verified without the record of the SHA that earned it',
     'test_verify_recomputes_the_bot_policy_from_the_selected_batch',
     '    st["verified_evidence"] = {"code_sha": code, "at": _now_utc(), "mode": "GO"}\n',
     '    pass\n'),
    ('R11-M1a',
     "the rollback prerequisite goes back to the exit status ALONE: a listing that exited 0 is accepted whether or not pct's closing `current` entry ends it",
     'test_r11_m1_a_listing_is_accepted_only_on_status_zero_and_pcts_closing_entry',
     '    if not listing_complete(listing.get("raw")):\n',
     '    if False:\n'),
    ('R11-M1b',
     'the closing entry is accepted ANYWHERE in the answer, so a listing with lines after it -- cut short on a rolled-back history, or with lines appended -- reads as whole',
     'test_r11_m1_a_listing_is_accepted_only_on_status_zero_and_pcts_closing_entry',
     '    return bool(lines) and bool(_LISTING_CLOSER.match(lines[-1]))\n',
     '    return any(_LISTING_CLOSER.match(l) for l in lines)\n'),
    ('R11-M1c',
     "the closing entry's pattern loses its anchors, so a last line that is the entry FOLLOWED by more text is accepted as pct's closing line",
     'test_r11_m1_a_listing_is_accepted_only_on_status_zero_and_pcts_closing_entry',
     '_LISTING_CLOSER = re.compile(r"\\A`->[ \\t]+current[ \\t]+You are here!\\Z")\n',
     '_LISTING_CLOSER = re.compile(r"`->[ \\t]+current[ \\t]+You are here!")\n'),
    ('R11-M1d',
     'the two readings agree without comparing their completeness, so a second reading cut short is not a picture of a different moment',
     'test_r11_m1_a_listing_is_accepted_only_on_status_zero_and_pcts_closing_entry',
     '                       and before["rc"] == after["rc"]\n                       and listing_complete(before["raw"]) == listing_complete(after["raw"]))\n',
     '                       and before["rc"] == after["rc"])\n'),
    ('R11-M1e',
     'the closing entry is SEARCHED for inside the last line instead of being the whole of it, so a snapshot whose description spells the entry closes a listing',
     'test_r11_m1_a_listing_is_accepted_only_on_status_zero_and_pcts_closing_entry',
     '    return bool(lines) and bool(_LISTING_CLOSER.match(lines[-1]))\n',
     '    return bool(lines) and bool(re.search(r"`->[ \\t]+current[ \\t]+You are here!\\Z", lines[-1]))\n'),
    ('R11-M1f',
     'the listing stops taking the YAML item marker off each line, so the whole listing the '
     'controller prints reads as unfinished',
     'test_r11_m1_the_listing_is_read_in_the_yaml_form_the_controller_prints',
     '        line = _DEBUG_ITEM.sub("", line.strip(), count=1)\n',
     '        line = line.strip()\n'),
    ('R11-B11a',
     'the capture writes a file again, beside printing its records',
     'test_the_capture_prints_records_and_writes_no_file',
     '    print(CAPTURE_OPEN)\n',
     '    open(os.devnull, "w").close()\n    print(CAPTURE_OPEN)\n'),
    ('R11-B11b',
     "the capture's pre-print self-check is gone, so a composer that appends the wrapper's own prose prints it",
     'test_the_captured_listing_is_built_from_records_and_everything_else_is_dropped',
     '        if line in CAPTURE_HEADER or record_line.match(line):\n            continue\n',
     '        if True:\n            continue\n'),
    ('R11-B11c',
     'the capture prints each line as it checks it, so a refusal leaves half a capture -- and the refused line -- in the transcript',
     'test_the_captured_listing_is_built_from_records_and_everything_else_is_dropped',
     '    for i, line in enumerate(text, 1):\n        if line in CAPTURE_HEADER',
     '    for i, line in enumerate(text, 1):\n        print(line)\n        if line in CAPTURE_HEADER'),
    ('R12-M1a',
     "the gate's names go back to whole tokens found ANYWHERE in the listing, so a deleted rollback point whose name another snapshot's description carries reads as listed and the deploy walks on",
     'test_r12_m1_a_name_only_in_a_description_is_not_a_listed_snapshot',
     '    for name, _rest in listing_entries(raw):\n',
     '    for name in [tok.strip(_TOKEN_EDGES) for tok in (raw or "").split()]:\n'),
    ('R12-M1b',
     "the zone may start any run of whitespace after the seconds again, so a description that begins with a zone word makes a wall clock read as a zoned moment",
     'test_r12_m1_a_name_only_in_a_description_is_not_a_listed_snapshot',
     '                        r"(?:[ ]?(Z|UTC|GMT|[+-][0-9]{2}:?[0-9]{2})(?=\\s|\\Z))?")\n',
     '                        r"(?:\\s*(Z|UTC|GMT|[+-][0-9]{2}:?[0-9]{2})(?=\\s|\\Z))?")\n'),
    ('R12-M1c',
     "the moment beside a name is read from any entry whose DESCRIPTION carries the name, so another snapshot's time answers for a rollback point that is not listed",
     'test_r12_m1_a_name_only_in_a_description_is_not_a_listed_snapshot',
     '        if entry != name:\n            continue\n        m = _LISTED_AT.match(rest)\n',
     '        if entry != name and name not in rest.split():\n            continue\n        m = _LISTED_AT.match(rest)\n'),
    ('R12-M1d',
     "the capture's records go back to whole tokens found anywhere on a line, so a name carried only by a description is written as a SNAPSHOT record",
     'test_r12_m1_a_name_only_in_a_description_is_not_a_listed_snapshot',
     '        entry = listing_entries(raw)\n',
     '        entry = [(n, raw.split(n, 1)[-1].strip()) for n in minted_names(raw)][:1]\n'),
    ('R12-M1e',
     "the play's own output is read by the listing's name-field reader, so the name the wrapper echoes is not found and no snapshot this train takes is ever recorded",
     'test_phase_zero_takes_a_fresh_snapshot_when_the_recorded_one_is_no_longer_listed',
     '    names = minted_names(play_out)\n',
     '    names = cc_names(play_out)\n'),
    ('R12-L2a',
     'the composed playbook is written to a temporary file on the controller again, run from it and removed',
     'test_r12_l2_the_playbook_reaches_the_controller_as_a_pipe_and_no_file_is_written',
     '    inner = ("cd ~/zap && source .venv/bin/activate && "\n             "ansible-playbook <(printf %%s %s | base64 -d) --limit %s -e scr_nonce=%s%s%s"\n',
     '    inner = ("cd ~/zap && source .venv/bin/activate && P=$(mktemp) && "\n             "printf %%s %s | base64 -d > \\"$P\\" && "\n             "ansible-playbook \\"$P\\" --limit %s -e scr_nonce=%s%s%s"\n             "; __scr_rc=$?; rm -f \\"$P\\"; exit $__scr_rc"\n'),
]
