#!/usr/bin/env python3
"""Generate `name_coverage.json` — the code points the renderer can draw.

The coverage projection `C` (v22 §2.4) removes from a public render name every
code point the Player Cards renderer has no glyph for, because the alternative
is a card with a row of tofu boxes on it under a `face_rev` that promises those
boxes are the right picture.

"Can draw" is not a judgement call: it is the union of the character maps of
the six fonts in `pc_face._FONT_FILES`, read THROUGH pc_face's own cmap parser
so the manifest and the renderer cannot disagree about the same font.

    python build_name_coverage.py            # rewrite the manifest
    python build_name_coverage.py --check    # exit 1 if it is out of date

The fonts are gitignored and fetched by `assets/fonts/fetch_fonts.py`; run that
first on a fresh checkout. The manifest itself IS committed: both boxes must
project names identically, and it is an input to `renderer_fp`.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "name_coverage.json")

# The "always drawable" set comes from pc_face, not from a second copy here:
# the generator's own list and `_has_glyph`'s list had drifted apart (this one
# was missing U+200C and the U+E0100 selectors, and `_has_glyph`'s was missing
# the space), and the manifest was built from THIS one while the renderer drew
# through the other.


def _pc_face():
    sys.path.insert(0, os.path.normpath(os.path.join(HERE, "..", "..")))
    import pc_face
    return pc_face


def _ranges(points):
    out = []
    for codepoint in sorted(points):
        if out and codepoint == out[-1][1] + 1:
            out[-1][1] = codepoint
        else:
            out.append([codepoint, codepoint])
    return out


def build():
    pc_face = _pc_face()
    always = set(pc_face._ALWAYS_GLYPH)
    per_role, covered = {}, set(always)
    for role, name in sorted(pc_face._FONT_FILES.items()):
        path = pc_face._FONTS_PATH / name
        if not path.is_file():
            raise SystemExit("missing font %s — run assets/fonts/fetch_fonts.py first" % name)
        tables = pc_face._font_tables(path.read_bytes())
        points = pc_face._Cmap(tables["cmap"]).covered()
        per_role[role] = points
        covered |= points
    return {
        "version": 2,
        "note": ("What each renderer ROLE can draw, plus the candidate order the "
                 "run splitter tries. Per role and not a flat union, because the "
                 "renderer needs ONE font to cover a whole grapheme cluster: a "
                 "cluster whose code points are covered by different fonts is a "
                 "box on the card. Generated by build_name_coverage.py from "
                 "pc_face's own cmap parser; a test asserts it still matches."),
        "always": _ranges(always),
        "roles": {role: _ranges(points) for role, points in sorted(per_role.items())},
        "candidates": {base: list(pc_face.candidate_roles(base))
                       for base in pc_face.BASE_ROLES},
        "emoji_role": "emoji",
        "emoji_pattern": pc_face._EMOJI_RE.pattern,
        "fonts": {pc_face._FONT_FILES[role]: len(points)
                  for role, points in sorted(per_role.items())},
        "count": len(covered),
        "ranges": _ranges(covered),
    }


def main(argv):
    built = build()
    if "--check" in argv:
        if not os.path.exists(OUT):
            print("name_coverage.json does not exist", file=sys.stderr)
            return 1
        with open(OUT, encoding="utf-8") as f:
            have = json.load(f)
        drift = [key for key in ("always", "roles", "candidates", "ranges", "emoji_role",
                                 "emoji_pattern")
                 if have.get(key) != built[key]]
        if drift:
            print("name_coverage.json is out of date: %s differ" % ", ".join(drift),
                  file=sys.stderr)
            return 1
        print("name_coverage.json is current: %d code points in %d ranges"
              % (built["count"], len(built["ranges"])))
        return 0
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(built, f, indent=1, sort_keys=True)
        f.write("\n")
    print("wrote %s: %d code points in %d ranges" % (OUT, built["count"], len(built["ranges"])))
    for name, n in sorted(built["fonts"].items()):
        print("  %-32s %6d" % (name, n))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
